// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -666507235;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__settings__clear_memories_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clear_memories",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::settings::clear_memories(api_discovery_timeout_secs)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__settings__delete_memory_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_memory",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::settings::delete_memory(
                            api_id,
                            api_discovery_timeout_secs,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__settings__delete_speaker_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_speaker",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::settings::delete_speaker(
                            api_id,
                            api_discovery_timeout_secs,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__engine_greeting_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_greeting",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::engine::engine_greeting(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__engine_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::engine::engine_version())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__settings__fetch_orchestrator_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_orchestrator_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::settings::fetch_orchestrator_settings(
                            api_discovery_timeout_secs,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::engine::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__engine__is_wake_word_engine_running_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_wake_word_engine_running",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::engine::is_wake_word_engine_running())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__settings__list_memories_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_memories",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::settings::list_memories(api_discovery_timeout_secs)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__settings__list_models_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_models",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::settings::list_models(api_discovery_timeout_secs)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__settings__list_speakers_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_speakers",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::settings::list_speakers(api_discovery_timeout_secs)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__settings__merge_speakers_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "merge_speakers",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_keep = <String>::sse_decode(&mut deserializer);
            let api_drop = <String>::sse_decode(&mut deserializer);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::settings::merge_speakers(
                            api_keep,
                            api_drop,
                            api_discovery_timeout_secs,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__settings__name_speaker_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "name_speaker",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::settings::name_speaker(
                            api_id,
                            api_name,
                            api_discovery_timeout_secs,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__start_wake_word_engine_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_wake_word_engine",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::engine::WakeWordConfig>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::engine::WakeWordEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::engine::start_wake_word_engine(api_config, api_sink)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__engine__stop_wake_word_engine_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_wake_word_engine",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::engine::stop_wake_word_engine();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__settings__update_orchestrator_settings_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_orchestrator_settings",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_update = <crate::api::settings::SettingsUpdate>::sse_decode(&mut deserializer);
            let api_discovery_timeout_secs = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::settings::update_orchestrator_settings(
                            api_update,
                            api_discovery_timeout_secs,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::engine::WakeWordEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::settings::MemoryEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settings::MemoryEntry>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::settings::ModelInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settings::ModelInfo>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::settings::SpeakerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::settings::SpeakerInfo>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::settings::MemoryEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_createdAt = <i64>::sse_decode(deserializer);
        return crate::api::settings::MemoryEntry {
            id: var_id,
            kind: var_kind,
            content: var_content,
            source: var_source,
            created_at: var_createdAt,
        };
    }
}

impl SseDecode for crate::api::settings::ModelInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_provider = <String>::sse_decode(deserializer);
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        return crate::api::settings::ModelInfo {
            provider: var_provider,
            id: var_id,
            label: var_label,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::settings::OrchestratorSettings {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_llmBackend = <String>::sse_decode(deserializer);
        let mut var_llmModel = <Option<String>>::sse_decode(deserializer);
        let mut var_anthropicAuth = <String>::sse_decode(deserializer);
        let mut var_ttsVoice = <Option<String>>::sse_decode(deserializer);
        let mut var_endSilenceMs = <u32>::sse_decode(deserializer);
        let mut var_voiceRmsThreshold = <f64>::sse_decode(deserializer);
        return crate::api::settings::OrchestratorSettings {
            ok: var_ok,
            message: var_message,
            llm_backend: var_llmBackend,
            llm_model: var_llmModel,
            anthropic_auth: var_anthropicAuth,
            tts_voice: var_ttsVoice,
            end_silence_ms: var_endSilenceMs,
            voice_rms_threshold: var_voiceRmsThreshold,
        };
    }
}

impl SseDecode for crate::api::settings::SettingsUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_llmBackend = <Option<String>>::sse_decode(deserializer);
        let mut var_llmModel = <Option<String>>::sse_decode(deserializer);
        let mut var_anthropicAuth = <Option<String>>::sse_decode(deserializer);
        let mut var_setTtsVoice = <bool>::sse_decode(deserializer);
        let mut var_ttsVoice = <Option<String>>::sse_decode(deserializer);
        let mut var_endSilenceMs = <Option<u32>>::sse_decode(deserializer);
        let mut var_voiceRmsThreshold = <Option<f64>>::sse_decode(deserializer);
        return crate::api::settings::SettingsUpdate {
            llm_backend: var_llmBackend,
            llm_model: var_llmModel,
            anthropic_auth: var_anthropicAuth,
            set_tts_voice: var_setTtsVoice,
            tts_voice: var_ttsVoice,
            end_silence_ms: var_endSilenceMs,
            voice_rms_threshold: var_voiceRmsThreshold,
        };
    }
}

impl SseDecode for crate::api::settings::SpeakerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_labeled = <bool>::sse_decode(deserializer);
        let mut var_samples = <i64>::sse_decode(deserializer);
        let mut var_createdAt = <i64>::sse_decode(deserializer);
        return crate::api::settings::SpeakerInfo {
            id: var_id,
            name: var_name,
            labeled: var_labeled,
            samples: var_samples,
            created_at: var_createdAt,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::engine::WakeWordConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_melspecModelPath = <String>::sse_decode(deserializer);
        let mut var_embeddingModelPath = <String>::sse_decode(deserializer);
        let mut var_wakewordModelPath = <String>::sse_decode(deserializer);
        let mut var_modelName = <String>::sse_decode(deserializer);
        let mut var_threshold = <f32>::sse_decode(deserializer);
        let mut var_activeThreshold = <f32>::sse_decode(deserializer);
        let mut var_discoveryTimeoutSecs = <u64>::sse_decode(deserializer);
        let mut var_turnTimeoutSecs = <u64>::sse_decode(deserializer);
        let mut var_smoothingWindow = <u32>::sse_decode(deserializer);
        let mut var_fireOnPeak = <bool>::sse_decode(deserializer);
        let mut var_playbackBufferSecs = <u32>::sse_decode(deserializer);
        let mut var_useAudiorecord = <bool>::sse_decode(deserializer);
        let mut var_micSource = <u32>::sse_decode(deserializer);
        let mut var_platformAec = <bool>::sse_decode(deserializer);
        let mut var_platformAgc = <bool>::sse_decode(deserializer);
        let mut var_platformNs = <bool>::sse_decode(deserializer);
        return crate::api::engine::WakeWordConfig {
            melspec_model_path: var_melspecModelPath,
            embedding_model_path: var_embeddingModelPath,
            wakeword_model_path: var_wakewordModelPath,
            model_name: var_modelName,
            threshold: var_threshold,
            active_threshold: var_activeThreshold,
            discovery_timeout_secs: var_discoveryTimeoutSecs,
            turn_timeout_secs: var_turnTimeoutSecs,
            smoothing_window: var_smoothingWindow,
            fire_on_peak: var_fireOnPeak,
            playback_buffer_secs: var_playbackBufferSecs,
            use_audiorecord: var_useAudiorecord,
            mic_source: var_micSource,
            platform_aec: var_platformAec,
            platform_agc: var_platformAgc,
            platform_ns: var_platformNs,
        };
    }
}

impl SseDecode for crate::api::engine::WakeWordEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::engine::WakeWordEventKind>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_device = <String>::sse_decode(deserializer);
        let mut var_deviceSampleRate = <u32>::sse_decode(deserializer);
        let mut var_channels = <u16>::sse_decode(deserializer);
        let mut var_rms = <f32>::sse_decode(deserializer);
        let mut var_score = <f32>::sse_decode(deserializer);
        let mut var_model = <String>::sse_decode(deserializer);
        let mut var_transcript = <String>::sse_decode(deserializer);
        let mut var_reply = <String>::sse_decode(deserializer);
        let mut var_timerId = <u32>::sse_decode(deserializer);
        let mut var_timerLabel = <String>::sse_decode(deserializer);
        let mut var_timerRemainingSecs = <u32>::sse_decode(deserializer);
        return crate::api::engine::WakeWordEvent {
            kind: var_kind,
            message: var_message,
            device: var_device,
            device_sample_rate: var_deviceSampleRate,
            channels: var_channels,
            rms: var_rms,
            score: var_score,
            model: var_model,
            transcript: var_transcript,
            reply: var_reply,
            timer_id: var_timerId,
            timer_label: var_timerLabel,
            timer_remaining_secs: var_timerRemainingSecs,
        };
    }
}

impl SseDecode for crate::api::engine::WakeWordEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::engine::WakeWordEventKind::Started,
            1 => crate::api::engine::WakeWordEventKind::Status,
            2 => crate::api::engine::WakeWordEventKind::Level,
            3 => crate::api::engine::WakeWordEventKind::Detected,
            4 => crate::api::engine::WakeWordEventKind::Connecting,
            5 => crate::api::engine::WakeWordEventKind::Streaming,
            6 => crate::api::engine::WakeWordEventKind::Transcript,
            7 => crate::api::engine::WakeWordEventKind::ReplyToken,
            8 => crate::api::engine::WakeWordEventKind::Speaking,
            9 => crate::api::engine::WakeWordEventKind::Disconnected,
            10 => crate::api::engine::WakeWordEventKind::Stopped,
            11 => crate::api::engine::WakeWordEventKind::Error,
            12 => crate::api::engine::WakeWordEventKind::TimerStarted,
            13 => crate::api::engine::WakeWordEventKind::TimerFinished,
            14 => crate::api::engine::WakeWordEventKind::TimerCancelled,
            _ => unreachable!("Invalid variant for WakeWordEventKind: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__settings__clear_memories_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__settings__delete_memory_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__settings__delete_speaker_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__settings__fetch_orchestrator_settings_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__engine__init_app_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__settings__list_memories_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__settings__list_models_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__settings__list_speakers_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__settings__merge_speakers_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__settings__name_speaker_impl(port, ptr, rust_vec_len, data_len),
        14 => {
            wire__crate__api__engine__start_wake_word_engine_impl(port, ptr, rust_vec_len, data_len)
        }
        15 => {
            wire__crate__api__engine__stop_wake_word_engine_impl(port, ptr, rust_vec_len, data_len)
        }
        16 => wire__crate__api__settings__update_orchestrator_settings_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        4 => wire__crate__api__engine__engine_greeting_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__engine__engine_version_impl(ptr, rust_vec_len, data_len),
        8 => {
            wire__crate__api__engine__is_wake_word_engine_running_impl(ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settings::MemoryEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settings::MemoryEntry
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settings::MemoryEntry>
    for crate::api::settings::MemoryEntry
{
    fn into_into_dart(self) -> crate::api::settings::MemoryEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settings::ModelInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.provider.into_into_dart().into_dart(),
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settings::ModelInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settings::ModelInfo>
    for crate::api::settings::ModelInfo
{
    fn into_into_dart(self) -> crate::api::settings::ModelInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settings::OrchestratorSettings {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.llm_backend.into_into_dart().into_dart(),
            self.llm_model.into_into_dart().into_dart(),
            self.anthropic_auth.into_into_dart().into_dart(),
            self.tts_voice.into_into_dart().into_dart(),
            self.end_silence_ms.into_into_dart().into_dart(),
            self.voice_rms_threshold.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settings::OrchestratorSettings
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settings::OrchestratorSettings>
    for crate::api::settings::OrchestratorSettings
{
    fn into_into_dart(self) -> crate::api::settings::OrchestratorSettings {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settings::SettingsUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.llm_backend.into_into_dart().into_dart(),
            self.llm_model.into_into_dart().into_dart(),
            self.anthropic_auth.into_into_dart().into_dart(),
            self.set_tts_voice.into_into_dart().into_dart(),
            self.tts_voice.into_into_dart().into_dart(),
            self.end_silence_ms.into_into_dart().into_dart(),
            self.voice_rms_threshold.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settings::SettingsUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settings::SettingsUpdate>
    for crate::api::settings::SettingsUpdate
{
    fn into_into_dart(self) -> crate::api::settings::SettingsUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::settings::SpeakerInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.labeled.into_into_dart().into_dart(),
            self.samples.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::settings::SpeakerInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::settings::SpeakerInfo>
    for crate::api::settings::SpeakerInfo
{
    fn into_into_dart(self) -> crate::api::settings::SpeakerInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::WakeWordConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.melspec_model_path.into_into_dart().into_dart(),
            self.embedding_model_path.into_into_dart().into_dart(),
            self.wakeword_model_path.into_into_dart().into_dart(),
            self.model_name.into_into_dart().into_dart(),
            self.threshold.into_into_dart().into_dart(),
            self.active_threshold.into_into_dart().into_dart(),
            self.discovery_timeout_secs.into_into_dart().into_dart(),
            self.turn_timeout_secs.into_into_dart().into_dart(),
            self.smoothing_window.into_into_dart().into_dart(),
            self.fire_on_peak.into_into_dart().into_dart(),
            self.playback_buffer_secs.into_into_dart().into_dart(),
            self.use_audiorecord.into_into_dart().into_dart(),
            self.mic_source.into_into_dart().into_dart(),
            self.platform_aec.into_into_dart().into_dart(),
            self.platform_agc.into_into_dart().into_dart(),
            self.platform_ns.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::WakeWordConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::WakeWordConfig>
    for crate::api::engine::WakeWordConfig
{
    fn into_into_dart(self) -> crate::api::engine::WakeWordConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::WakeWordEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.device.into_into_dart().into_dart(),
            self.device_sample_rate.into_into_dart().into_dart(),
            self.channels.into_into_dart().into_dart(),
            self.rms.into_into_dart().into_dart(),
            self.score.into_into_dart().into_dart(),
            self.model.into_into_dart().into_dart(),
            self.transcript.into_into_dart().into_dart(),
            self.reply.into_into_dart().into_dart(),
            self.timer_id.into_into_dart().into_dart(),
            self.timer_label.into_into_dart().into_dart(),
            self.timer_remaining_secs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::WakeWordEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::WakeWordEvent>
    for crate::api::engine::WakeWordEvent
{
    fn into_into_dart(self) -> crate::api::engine::WakeWordEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::WakeWordEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Started => 0.into_dart(),
            Self::Status => 1.into_dart(),
            Self::Level => 2.into_dart(),
            Self::Detected => 3.into_dart(),
            Self::Connecting => 4.into_dart(),
            Self::Streaming => 5.into_dart(),
            Self::Transcript => 6.into_dart(),
            Self::ReplyToken => 7.into_dart(),
            Self::Speaking => 8.into_dart(),
            Self::Disconnected => 9.into_dart(),
            Self::Stopped => 10.into_dart(),
            Self::Error => 11.into_dart(),
            Self::TimerStarted => 12.into_dart(),
            Self::TimerFinished => 13.into_dart(),
            Self::TimerCancelled => 14.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::engine::WakeWordEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::WakeWordEventKind>
    for crate::api::engine::WakeWordEventKind
{
    fn into_into_dart(self) -> crate::api::engine::WakeWordEventKind {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::engine::WakeWordEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::settings::MemoryEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settings::MemoryEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::settings::ModelInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settings::ModelInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::settings::SpeakerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::settings::SpeakerInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::settings::MemoryEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.content, serializer);
        <String>::sse_encode(self.source, serializer);
        <i64>::sse_encode(self.created_at, serializer);
    }
}

impl SseEncode for crate::api::settings::ModelInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.provider, serializer);
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::settings::OrchestratorSettings {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <String>::sse_encode(self.message, serializer);
        <String>::sse_encode(self.llm_backend, serializer);
        <Option<String>>::sse_encode(self.llm_model, serializer);
        <String>::sse_encode(self.anthropic_auth, serializer);
        <Option<String>>::sse_encode(self.tts_voice, serializer);
        <u32>::sse_encode(self.end_silence_ms, serializer);
        <f64>::sse_encode(self.voice_rms_threshold, serializer);
    }
}

impl SseEncode for crate::api::settings::SettingsUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.llm_backend, serializer);
        <Option<String>>::sse_encode(self.llm_model, serializer);
        <Option<String>>::sse_encode(self.anthropic_auth, serializer);
        <bool>::sse_encode(self.set_tts_voice, serializer);
        <Option<String>>::sse_encode(self.tts_voice, serializer);
        <Option<u32>>::sse_encode(self.end_silence_ms, serializer);
        <Option<f64>>::sse_encode(self.voice_rms_threshold, serializer);
    }
}

impl SseEncode for crate::api::settings::SpeakerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <Option<String>>::sse_encode(self.name, serializer);
        <bool>::sse_encode(self.labeled, serializer);
        <i64>::sse_encode(self.samples, serializer);
        <i64>::sse_encode(self.created_at, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::engine::WakeWordConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.melspec_model_path, serializer);
        <String>::sse_encode(self.embedding_model_path, serializer);
        <String>::sse_encode(self.wakeword_model_path, serializer);
        <String>::sse_encode(self.model_name, serializer);
        <f32>::sse_encode(self.threshold, serializer);
        <f32>::sse_encode(self.active_threshold, serializer);
        <u64>::sse_encode(self.discovery_timeout_secs, serializer);
        <u64>::sse_encode(self.turn_timeout_secs, serializer);
        <u32>::sse_encode(self.smoothing_window, serializer);
        <bool>::sse_encode(self.fire_on_peak, serializer);
        <u32>::sse_encode(self.playback_buffer_secs, serializer);
        <bool>::sse_encode(self.use_audiorecord, serializer);
        <u32>::sse_encode(self.mic_source, serializer);
        <bool>::sse_encode(self.platform_aec, serializer);
        <bool>::sse_encode(self.platform_agc, serializer);
        <bool>::sse_encode(self.platform_ns, serializer);
    }
}

impl SseEncode for crate::api::engine::WakeWordEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::engine::WakeWordEventKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.message, serializer);
        <String>::sse_encode(self.device, serializer);
        <u32>::sse_encode(self.device_sample_rate, serializer);
        <u16>::sse_encode(self.channels, serializer);
        <f32>::sse_encode(self.rms, serializer);
        <f32>::sse_encode(self.score, serializer);
        <String>::sse_encode(self.model, serializer);
        <String>::sse_encode(self.transcript, serializer);
        <String>::sse_encode(self.reply, serializer);
        <u32>::sse_encode(self.timer_id, serializer);
        <String>::sse_encode(self.timer_label, serializer);
        <u32>::sse_encode(self.timer_remaining_secs, serializer);
    }
}

impl SseEncode for crate::api::engine::WakeWordEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::engine::WakeWordEventKind::Started => 0,
                crate::api::engine::WakeWordEventKind::Status => 1,
                crate::api::engine::WakeWordEventKind::Level => 2,
                crate::api::engine::WakeWordEventKind::Detected => 3,
                crate::api::engine::WakeWordEventKind::Connecting => 4,
                crate::api::engine::WakeWordEventKind::Streaming => 5,
                crate::api::engine::WakeWordEventKind::Transcript => 6,
                crate::api::engine::WakeWordEventKind::ReplyToken => 7,
                crate::api::engine::WakeWordEventKind::Speaking => 8,
                crate::api::engine::WakeWordEventKind::Disconnected => 9,
                crate::api::engine::WakeWordEventKind::Stopped => 10,
                crate::api::engine::WakeWordEventKind::Error => 11,
                crate::api::engine::WakeWordEventKind::TimerStarted => 12,
                crate::api::engine::WakeWordEventKind::TimerFinished => 13,
                crate::api::engine::WakeWordEventKind::TimerCancelled => 14,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
