// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEngineInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1294313178;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_ambient_display',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiSettingsClearMemories({
    required BigInt discoveryTimeoutSecs,
  });

  Future<bool> crateApiSettingsDeleteMemory({
    required PlatformInt64 id,
    required BigInt discoveryTimeoutSecs,
  });

  String crateApiEngineEngineGreeting({required String name});

  String crateApiEngineEngineVersion();

  Future<OrchestratorSettings> crateApiSettingsFetchOrchestratorSettings({
    required BigInt discoveryTimeoutSecs,
  });

  Future<void> crateApiEngineInitApp();

  bool crateApiEngineIsWakeWordEngineRunning();

  Future<List<MemoryEntry>> crateApiSettingsListMemories({
    required BigInt discoveryTimeoutSecs,
  });

  Stream<WakeWordEvent> crateApiEngineStartWakeWordEngine({
    required WakeWordConfig config,
  });

  Future<void> crateApiEngineStopWakeWordEngine();

  Future<OrchestratorSettings> crateApiSettingsUpdateOrchestratorSettings({
    required SettingsUpdate update,
    required BigInt discoveryTimeoutSecs,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiSettingsClearMemories({
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsClearMemoriesConstMeta,
        argValues: [discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsClearMemoriesConstMeta =>
      const TaskConstMeta(
        debugName: "clear_memories",
        argNames: ["discoveryTimeoutSecs"],
      );

  @override
  Future<bool> crateApiSettingsDeleteMemory({
    required PlatformInt64 id,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsDeleteMemoryConstMeta,
        argValues: [id, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsDeleteMemoryConstMeta =>
      const TaskConstMeta(
        debugName: "delete_memory",
        argNames: ["id", "discoveryTimeoutSecs"],
      );

  @override
  String crateApiEngineEngineGreeting({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineGreetingConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineGreetingConstMeta =>
      const TaskConstMeta(debugName: "engine_greeting", argNames: ["name"]);

  @override
  String crateApiEngineEngineVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineVersionConstMeta =>
      const TaskConstMeta(debugName: "engine_version", argNames: []);

  @override
  Future<OrchestratorSettings> crateApiSettingsFetchOrchestratorSettings({
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_orchestrator_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsFetchOrchestratorSettingsConstMeta,
        argValues: [discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsFetchOrchestratorSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_orchestrator_settings",
        argNames: ["discoveryTimeoutSecs"],
      );

  @override
  Future<void> crateApiEngineInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiEngineIsWakeWordEngineRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineIsWakeWordEngineRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineIsWakeWordEngineRunningConstMeta =>
      const TaskConstMeta(
        debugName: "is_wake_word_engine_running",
        argNames: [],
      );

  @override
  Future<List<MemoryEntry>> crateApiSettingsListMemories({
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsListMemoriesConstMeta,
        argValues: [discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsListMemoriesConstMeta =>
      const TaskConstMeta(
        debugName: "list_memories",
        argNames: ["discoveryTimeoutSecs"],
      );

  @override
  Stream<WakeWordEvent> crateApiEngineStartWakeWordEngine({
    required WakeWordConfig config,
  }) {
    final sink = RustStreamSink<WakeWordEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_wake_word_config(config, serializer);
            sse_encode_StreamSink_wake_word_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineStartWakeWordEngineConstMeta,
          argValues: [config, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineStartWakeWordEngineConstMeta =>
      const TaskConstMeta(
        debugName: "start_wake_word_engine",
        argNames: ["config", "sink"],
      );

  @override
  Future<void> crateApiEngineStopWakeWordEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineStopWakeWordEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineStopWakeWordEngineConstMeta =>
      const TaskConstMeta(debugName: "stop_wake_word_engine", argNames: []);

  @override
  Future<OrchestratorSettings> crateApiSettingsUpdateOrchestratorSettings({
    required SettingsUpdate update,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_settings_update(update, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_orchestrator_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsUpdateOrchestratorSettingsConstMeta,
        argValues: [update, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsUpdateOrchestratorSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "update_orchestrator_settings",
        argNames: ["update", "discoveryTimeoutSecs"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<WakeWordEvent> dco_decode_StreamSink_wake_word_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SettingsUpdate dco_decode_box_autoadd_settings_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings_update(raw);
  }

  @protected
  WakeWordConfig dco_decode_box_autoadd_wake_word_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wake_word_config(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<MemoryEntry> dco_decode_list_memory_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_memory_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MemoryEntry dco_decode_memory_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MemoryEntry(
      id: dco_decode_i_64(arr[0]),
      kind: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      source: dco_decode_String(arr[3]),
      createdAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  OrchestratorSettings dco_decode_orchestrator_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OrchestratorSettings(
      ok: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      llmBackend: dco_decode_String(arr[2]),
      llmModel: dco_decode_opt_String(arr[3]),
      ttsVoice: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  SettingsUpdate dco_decode_settings_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SettingsUpdate(
      llmBackend: dco_decode_opt_String(arr[0]),
      llmModel: dco_decode_opt_String(arr[1]),
      setTtsVoice: dco_decode_bool(arr[2]),
      ttsVoice: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WakeWordConfig dco_decode_wake_word_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return WakeWordConfig(
      melspecModelPath: dco_decode_String(arr[0]),
      embeddingModelPath: dco_decode_String(arr[1]),
      wakewordModelPath: dco_decode_String(arr[2]),
      modelName: dco_decode_String(arr[3]),
      threshold: dco_decode_f_32(arr[4]),
      activeThreshold: dco_decode_f_32(arr[5]),
      discoveryTimeoutSecs: dco_decode_u_64(arr[6]),
      turnTimeoutSecs: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  WakeWordEvent dco_decode_wake_word_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return WakeWordEvent(
      kind: dco_decode_wake_word_event_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      device: dco_decode_String(arr[2]),
      deviceSampleRate: dco_decode_u_32(arr[3]),
      channels: dco_decode_u_16(arr[4]),
      rms: dco_decode_f_32(arr[5]),
      score: dco_decode_f_32(arr[6]),
      model: dco_decode_String(arr[7]),
      transcript: dco_decode_String(arr[8]),
      reply: dco_decode_String(arr[9]),
    );
  }

  @protected
  WakeWordEventKind dco_decode_wake_word_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WakeWordEventKind.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<WakeWordEvent> sse_decode_StreamSink_wake_word_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SettingsUpdate sse_decode_box_autoadd_settings_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings_update(deserializer));
  }

  @protected
  WakeWordConfig sse_decode_box_autoadd_wake_word_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wake_word_config(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<MemoryEntry> sse_decode_list_memory_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_memory_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MemoryEntry sse_decode_memory_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return MemoryEntry(
      id: var_id,
      kind: var_kind,
      content: var_content,
      source: var_source,
      createdAt: var_createdAt,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrchestratorSettings sse_decode_orchestrator_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_llmBackend = sse_decode_String(deserializer);
    var var_llmModel = sse_decode_opt_String(deserializer);
    var var_ttsVoice = sse_decode_opt_String(deserializer);
    return OrchestratorSettings(
      ok: var_ok,
      message: var_message,
      llmBackend: var_llmBackend,
      llmModel: var_llmModel,
      ttsVoice: var_ttsVoice,
    );
  }

  @protected
  SettingsUpdate sse_decode_settings_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_llmBackend = sse_decode_opt_String(deserializer);
    var var_llmModel = sse_decode_opt_String(deserializer);
    var var_setTtsVoice = sse_decode_bool(deserializer);
    var var_ttsVoice = sse_decode_opt_String(deserializer);
    return SettingsUpdate(
      llmBackend: var_llmBackend,
      llmModel: var_llmModel,
      setTtsVoice: var_setTtsVoice,
      ttsVoice: var_ttsVoice,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WakeWordConfig sse_decode_wake_word_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_melspecModelPath = sse_decode_String(deserializer);
    var var_embeddingModelPath = sse_decode_String(deserializer);
    var var_wakewordModelPath = sse_decode_String(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    var var_threshold = sse_decode_f_32(deserializer);
    var var_activeThreshold = sse_decode_f_32(deserializer);
    var var_discoveryTimeoutSecs = sse_decode_u_64(deserializer);
    var var_turnTimeoutSecs = sse_decode_u_64(deserializer);
    return WakeWordConfig(
      melspecModelPath: var_melspecModelPath,
      embeddingModelPath: var_embeddingModelPath,
      wakewordModelPath: var_wakewordModelPath,
      modelName: var_modelName,
      threshold: var_threshold,
      activeThreshold: var_activeThreshold,
      discoveryTimeoutSecs: var_discoveryTimeoutSecs,
      turnTimeoutSecs: var_turnTimeoutSecs,
    );
  }

  @protected
  WakeWordEvent sse_decode_wake_word_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_wake_word_event_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_device = sse_decode_String(deserializer);
    var var_deviceSampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_rms = sse_decode_f_32(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_transcript = sse_decode_String(deserializer);
    var var_reply = sse_decode_String(deserializer);
    return WakeWordEvent(
      kind: var_kind,
      message: var_message,
      device: var_device,
      deviceSampleRate: var_deviceSampleRate,
      channels: var_channels,
      rms: var_rms,
      score: var_score,
      model: var_model,
      transcript: var_transcript,
      reply: var_reply,
    );
  }

  @protected
  WakeWordEventKind sse_decode_wake_word_event_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WakeWordEventKind.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_wake_word_event_Sse(
    RustStreamSink<WakeWordEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_wake_word_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_settings_update(
    SettingsUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings_update(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_wake_word_config(
    WakeWordConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wake_word_config(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_memory_entry(
    List<MemoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_memory_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_memory_entry(MemoryEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_orchestrator_settings(
    OrchestratorSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.llmBackend, serializer);
    sse_encode_opt_String(self.llmModel, serializer);
    sse_encode_opt_String(self.ttsVoice, serializer);
  }

  @protected
  void sse_encode_settings_update(
    SettingsUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.llmBackend, serializer);
    sse_encode_opt_String(self.llmModel, serializer);
    sse_encode_bool(self.setTtsVoice, serializer);
    sse_encode_opt_String(self.ttsVoice, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wake_word_config(
    WakeWordConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.melspecModelPath, serializer);
    sse_encode_String(self.embeddingModelPath, serializer);
    sse_encode_String(self.wakewordModelPath, serializer);
    sse_encode_String(self.modelName, serializer);
    sse_encode_f_32(self.threshold, serializer);
    sse_encode_f_32(self.activeThreshold, serializer);
    sse_encode_u_64(self.discoveryTimeoutSecs, serializer);
    sse_encode_u_64(self.turnTimeoutSecs, serializer);
  }

  @protected
  void sse_encode_wake_word_event(
    WakeWordEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wake_word_event_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.device, serializer);
    sse_encode_u_32(self.deviceSampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_f_32(self.rms, serializer);
    sse_encode_f_32(self.score, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.transcript, serializer);
    sse_encode_String(self.reply, serializer);
  }

  @protected
  void sse_encode_wake_word_event_kind(
    WakeWordEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
