// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base`, `connecting`, `detected`, `disconnected`, `dismiss_recipe`, `engine_target`, `error`, `level`, `listening_followup`, `notify_slot`, `presence`, `reply_token`, `show_recipe`, `speaking_done`, `speaking`, `started`, `status`, `stopped`, `streaming`, `timer_cancelled`, `timer_finished`, `timer_started`, `transcript`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NotifyHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

/// A friendly greeting from the native Rust engine.
///
/// The Flutter UI calls this on startup to confirm the cross-compiled shared
/// library loaded and the FRB bridge is live on the device.
String engineGreeting({required String name}) =>
    RustLib.instance.api.crateApiEngineEngineGreeting(name: name);

/// Reports the native engine's version and build target so the device can show
/// exactly which cross-compiled binary it is running.
String engineVersion() => RustLib.instance.api.crateApiEngineEngineVersion();

/// Start microphone capture and continuous on-device wake-word scoring, pushing
/// [`WakeWordEvent`]s to Dart. Replaces any engine already running.
Stream<WakeWordEvent> startWakeWordEngine({required WakeWordConfig config}) =>
    RustLib.instance.api.crateApiEngineStartWakeWordEngine(config: config);

/// Stop the wake-word engine and release the microphone. Idempotent.
Future<void> stopWakeWordEngine() =>
    RustLib.instance.api.crateApiEngineStopWakeWordEngine();

/// Whether the wake-word engine is currently running.
bool isWakeWordEngineRunning() =>
    RustLib.instance.api.crateApiEngineIsWakeWordEngineRunning();

/// Register user activity that isn't camera motion — a voice turn or a screen touch
/// — so it resets the screen-dim countdown (and brightens the screen if it had
/// already dimmed). Flutter calls this on each voice-turn transition and on screen
/// touches. Safe to call any time: it's a no-op when camera proximity isn't running,
/// and a harmless no-op off Android (host tests, no camera).
void noteUserActivity() =>
    RustLib.instance.api.crateApiEngineNoteUserActivity();

/// Open the persistent proactive-notification channel and stream pushed
/// notifications to Dart. Replaces any channel already running (so it can be
/// restarted when the pinned orchestrator changes). The channel dials the pinned
/// orchestrator and reconnects with backoff for the life of the subscription.
Stream<NotifyEvent> startNotifyChannel({required NotifyConfig config}) =>
    RustLib.instance.api.crateApiEngineStartNotifyChannel(config: config);

/// Stop the proactive-notification channel (if any) and join its thread. Idempotent.
Future<void> stopNotifyChannel() =>
    RustLib.instance.api.crateApiEngineStopNotifyChannel();

/// Config for the persistent notify channel. The orchestrator is discovered over
/// mDNS at connect time (same as the voice path), so only the pin, the browse
/// timeout, and this display's id are configured here.
class NotifyConfig {
  /// Stable selection key (`instance_id` TXT) of the pinned orchestrator; empty =
  /// "Auto" (first available). Mirrors [`WakeWordConfig::orchestrator_key`] so the
  /// notify channel targets the same Mac the voice path does.
  final String orchestratorKey;

  /// Seconds to browse `_wyoming._tcp` before falling back to the cached host
  /// (0 = built-in default).
  final BigInt discoveryTimeoutSecs;

  /// A stable identifier for this display, sent in the `ambient-hello` frame so the
  /// orchestrator can key notifications per device (may be empty).
  final String deviceId;

  const NotifyConfig({
    required this.orchestratorKey,
    required this.discoveryTimeoutSecs,
    required this.deviceId,
  });

  @override
  int get hashCode =>
      orchestratorKey.hashCode ^
      discoveryTimeoutSecs.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotifyConfig &&
          runtimeType == other.runtimeType &&
          orchestratorKey == other.orchestratorKey &&
          discoveryTimeoutSecs == other.discoveryTimeoutSecs &&
          deviceId == other.deviceId;
}

/// One proactive notification pushed from the orchestrator, streamed to Flutter.
/// Modeled as a flat struct (like [`WakeWordEvent`]) so the FRB boundary stays
/// dependency-free.
class NotifyEvent {
  /// Stable notification id (for dedup / dismiss on the UI side).
  final String id;

  /// `"info"` | `"reminder"` | `"alert"` — drives the banner styling.
  final String priority;

  /// Short headline.
  final String title;

  /// Body text.
  final String body;

  const NotifyEvent({
    required this.id,
    required this.priority,
    required this.title,
    required this.body,
  });

  @override
  int get hashCode =>
      id.hashCode ^ priority.hashCode ^ title.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotifyEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          priority == other.priority &&
          title == other.title &&
          body == other.body;
}

/// Paths and tuning for the openWakeWord three-model chain plus the Phase-3
/// Wyoming turn. The Flutter layer resolves the model paths from bundled assets
/// or the settings screen (Phase 6) and hands them to the engine. The Wyoming
/// host itself is discovered over mDNS at turn time, so no address is configured
/// here (architecture.md §5).
class WakeWordConfig {
  /// Path to the melspectrogram ONNX model (`melspectrogram.onnx`).
  final String melspecModelPath;

  /// Path to the shared feature/embedding ONNX model (`embedding_model.onnx`).
  final String embeddingModelPath;

  /// Path to the wake-word classifier ONNX model (e.g. `alexa_v0.1.onnx`).
  final String wakewordModelPath;

  /// Human-readable wake-word name, echoed back on detection events.
  final String modelName;

  /// Confidence in [0, 1] above which a detection is reported while idle.
  final double threshold;

  /// Higher confidence required to fire *while a turn is already active*
  /// (streaming/speaking). This is the AEC-interim mitigation from the locked
  /// decisions: raise the bar during playback so the device's own speaker is
  /// less likely to self-trigger (Plan.MD §4). Set equal to `threshold` to
  /// disable. Clamped to at least `threshold` at runtime.
  final double activeThreshold;

  /// Seconds to browse `_wyoming._tcp` before falling back to the cached host
  /// (0 = use the built-in default).
  final BigInt discoveryTimeoutSecs;

  /// Stable selection key (`instance_id` TXT) of the orchestrator this display
  /// is pinned to. Empty = "Auto" (connect to the first available orchestrator).
  /// When set, discovery resolves *only* this orchestrator and stays offline if
  /// it is unreachable, rather than silently connecting to a different one.
  final String orchestratorKey;

  /// Seconds of server silence before a turn is defensively abandoned
  /// (0 = use the built-in default).
  final BigInt turnTimeoutSecs;

  /// Number of consecutive per-block scores smoothed before a detection can fire
  /// (0 = engine default). Lower = snappier / more sensitive to brief or faint
  /// wake words; higher = fewer single-frame false triggers. A/B-tunable from the
  /// settings screen to dial in far-field responsiveness on hardware.
  final int smoothingWindow;

  /// Detection-gate criterion. `false` (default) fires on the *average* of the
  /// smoothing window clearing `threshold`; `true` fires as soon as the *peak*
  /// score in the window clears it — far more responsive to short/quiet "hey
  /// jarvis" utterances (whose confidence peaks for a single block and is
  /// otherwise diluted by the surrounding low blocks) at the cost of a slightly
  /// higher false-trigger rate.
  final bool fireOnPeak;

  /// Speaker playback buffer depth in seconds (0 = engine default). Sized to hold
  /// a whole spoken reply so long TTS answers are not truncated when the network
  /// delivers audio faster than real-time playback drains it. A/B-tunable.
  final int playbackBufferSecs;

  /// **Android only.** Use the Kotlin `AudioRecord` capture layer instead of
  /// `cpal`, to reach the HAL's far-field `VOICE_RECOGNITION` source (array
  /// beamforming) + platform audio effects. `false` (default) keeps the `cpal`
  /// path; ignored entirely off-Android. A/B-tunable from the settings screen.
  final bool useAudiorecord;

  /// `android.media.MediaRecorder.AudioSource` for the AudioRecord path
  /// (6 = `VOICE_RECOGNITION`, 7 = `VOICE_COMMUNICATION`, 1 = `MIC`). Only used
  /// when `use_audiorecord` is set.
  final int micSource;

  /// Attach the platform `AcousticEchoCanceler` to the AudioRecord session (if the
  /// device offers it). Default off — the host-side WebRTC APM does AEC, and prior
  /// on-hardware testing found this device's platform AEC did not actually cancel.
  final bool platformAec;

  /// Attach the platform `AutomaticGainControl` to the AudioRecord session (if
  /// available). Helps the Echo Show's quiet far-field pickup.
  final bool platformAgc;

  /// Attach the platform `NoiseSuppressor` to the AudioRecord session (if available).
  final bool platformNs;

  /// **Android only.** Use the front camera as a proximity sensor: a cheap
  /// frame-motion detector runs on low-res luma frames and, when someone
  /// approaches, the UI brightens the idle screen (dimming again after a quiet
  /// period). `false` (default off-Android) disables the camera entirely — no
  /// frames are ever captured. See `camera/presence.rs` and Plan.MD §5.
  final bool cameraProximity;

  /// Mean absolute per-pixel luma delta (0..255) above which a frame counts as
  /// motion. `0` uses the engine default (`presence::DEFAULT_MOTION_THRESHOLD`).
  /// Lower = more sensitive (brightens on fainter/farther movement) at the cost of
  /// more false wakes from noise/lighting; A/B-tunable.
  final double proximityMotionThreshold;

  /// Seconds of no motion before the screen is allowed to dim again. `0` uses the
  /// engine default (`presence::DEFAULT_RELEASE`).
  final int proximityReleaseSecs;

  const WakeWordConfig({
    required this.melspecModelPath,
    required this.embeddingModelPath,
    required this.wakewordModelPath,
    required this.modelName,
    required this.threshold,
    required this.activeThreshold,
    required this.discoveryTimeoutSecs,
    required this.orchestratorKey,
    required this.turnTimeoutSecs,
    required this.smoothingWindow,
    required this.fireOnPeak,
    required this.playbackBufferSecs,
    required this.useAudiorecord,
    required this.micSource,
    required this.platformAec,
    required this.platformAgc,
    required this.platformNs,
    required this.cameraProximity,
    required this.proximityMotionThreshold,
    required this.proximityReleaseSecs,
  });

  @override
  int get hashCode =>
      melspecModelPath.hashCode ^
      embeddingModelPath.hashCode ^
      wakewordModelPath.hashCode ^
      modelName.hashCode ^
      threshold.hashCode ^
      activeThreshold.hashCode ^
      discoveryTimeoutSecs.hashCode ^
      orchestratorKey.hashCode ^
      turnTimeoutSecs.hashCode ^
      smoothingWindow.hashCode ^
      fireOnPeak.hashCode ^
      playbackBufferSecs.hashCode ^
      useAudiorecord.hashCode ^
      micSource.hashCode ^
      platformAec.hashCode ^
      platformAgc.hashCode ^
      platformNs.hashCode ^
      cameraProximity.hashCode ^
      proximityMotionThreshold.hashCode ^
      proximityReleaseSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WakeWordConfig &&
          runtimeType == other.runtimeType &&
          melspecModelPath == other.melspecModelPath &&
          embeddingModelPath == other.embeddingModelPath &&
          wakewordModelPath == other.wakewordModelPath &&
          modelName == other.modelName &&
          threshold == other.threshold &&
          activeThreshold == other.activeThreshold &&
          discoveryTimeoutSecs == other.discoveryTimeoutSecs &&
          orchestratorKey == other.orchestratorKey &&
          turnTimeoutSecs == other.turnTimeoutSecs &&
          smoothingWindow == other.smoothingWindow &&
          fireOnPeak == other.fireOnPeak &&
          playbackBufferSecs == other.playbackBufferSecs &&
          useAudiorecord == other.useAudiorecord &&
          micSource == other.micSource &&
          platformAec == other.platformAec &&
          platformAgc == other.platformAgc &&
          platformNs == other.platformNs &&
          cameraProximity == other.cameraProximity &&
          proximityMotionThreshold == other.proximityMotionThreshold &&
          proximityReleaseSecs == other.proximityReleaseSecs;
}

/// A single event streamed from the Rust engine to the Flutter UI. Modeled as a
/// flat struct with a `kind` tag (rather than a data-carrying enum) so the FRB
/// boundary stays dependency-free; fields not relevant to a given `kind` carry
/// neutral defaults. `Clone` lets the engine fan the sink out to the Phase-3
/// Wyoming turn task (which emits on the same stream).
class WakeWordEvent {
  final WakeWordEventKind kind;

  /// Status / error text (`Status`, `Error`).
  final String message;

  /// Capture device name (`Started`).
  final String device;

  /// Device-native capture rate in Hz (`Started`).
  final int deviceSampleRate;

  /// Device channel count before mono downmix (`Started`).
  final int channels;

  /// Input RMS level (`Level`).
  final double rms;

  /// Wake-word confidence in [0, 1] (`Detected`).
  final double score;

  /// Wake-word name that fired (`Detected`).
  final String model;

  /// Recognized speech (`Transcript`).
  final String transcript;

  /// One streamed reply-token fragment (`ReplyToken`).
  final String reply;

  /// Timer id (`TimerStarted` / `TimerFinished` / `TimerCancelled`). Stable for
  /// the life of one timer so the UI can add/remove the right chip.
  final int timerId;

  /// Timer's spoken label, empty when unlabeled (`TimerStarted`/`TimerFinished`).
  final String timerLabel;

  /// Full timer duration in seconds at start (`TimerStarted`); the UI counts down
  /// from `now + timer_remaining_secs`. Zero for finished/cancelled.
  final int timerRemainingSecs;

  /// Camera proximity state (`Presence`): `true` = someone approached (brighten),
  /// `false` = quiet long enough to dim. Neutral `false` for every other kind.
  final bool present;

  /// The parsed recipe as a JSON string (`ShowRecipe`); empty for every other kind.
  /// The UI decodes it into the recipe-mode tabs.
  final String recipeJson;

  const WakeWordEvent({
    required this.kind,
    required this.message,
    required this.device,
    required this.deviceSampleRate,
    required this.channels,
    required this.rms,
    required this.score,
    required this.model,
    required this.transcript,
    required this.reply,
    required this.timerId,
    required this.timerLabel,
    required this.timerRemainingSecs,
    required this.present,
    required this.recipeJson,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      device.hashCode ^
      deviceSampleRate.hashCode ^
      channels.hashCode ^
      rms.hashCode ^
      score.hashCode ^
      model.hashCode ^
      transcript.hashCode ^
      reply.hashCode ^
      timerId.hashCode ^
      timerLabel.hashCode ^
      timerRemainingSecs.hashCode ^
      present.hashCode ^
      recipeJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WakeWordEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          device == other.device &&
          deviceSampleRate == other.deviceSampleRate &&
          channels == other.channels &&
          rms == other.rms &&
          score == other.score &&
          model == other.model &&
          transcript == other.transcript &&
          reply == other.reply &&
          timerId == other.timerId &&
          timerLabel == other.timerLabel &&
          timerRemainingSecs == other.timerRemainingSecs &&
          present == other.present &&
          recipeJson == other.recipeJson;
}

/// Discriminates the kind of [`WakeWordEvent`]. A unit-only enum so FRB maps it
/// to a plain Dart `enum` (no `freezed` codegen dependency needed).
enum WakeWordEventKind {
  /// Capture started; `device`/`device_sample_rate`/`channels` are populated.
  started,

  /// Informational status in `message` (e.g. model loaded, capture-only).
  status,

  /// Periodic input level in `rms` (~0.0..1.0) — proves capture is live even
  /// before a wake-word model is present.
  level,

  /// The wake word fired; `model` and `score` are populated.
  detected,

  /// Phase 3: a turn began — discovering/dialing the Wyoming host. `message`
  /// describes the resolved endpoint when known.
  connecting,

  /// Phase 3: connected to the Wyoming host; PCM is now streaming up.
  streaming,

  /// Phase 3: a transcript arrived from the STT server; `transcript` carries
  /// the recognized text.
  transcript,

  /// Phase 5: one streamed LLM reply-token fragment; `reply` carries the text.
  /// The UI appends these to render the reply token-by-token.
  replyToken,

  /// Phase 5: the reply's TTS audio has started and is now playing back through
  /// the speakers.
  speaking,

  /// Phase 5: the reply's TTS audio has finished playing out of the speaker — the
  /// playback ring drained naturally, or was flushed by a barge-in. UI-only: it
  /// signals that the on-screen reply text may be removed now that the audio has
  /// stopped. Fires *after* the turn has already returned to idle, because the
  /// device relays audio faster than real-time (see `engine/net.rs`).
  speakingDone,

  /// Follow-up listening: the assistant's reply was a question, so the device
  /// reopened the mic and is listening for the answer **without a wake word** (a
  /// fresh turn is starting). UI-only cue so the screen can show a "listening for
  /// your reply" affordance. Followed by the usual `Streaming`/`Transcript`/… of
  /// the follow-up turn. See `plans/Plan.MD` (Follow-up listening).
  listeningFollowup,

  /// Phase 3: the turn ended / the socket dropped; `message` gives the reason.
  /// The engine returns to idle wake-word listening.
  disconnected,

  /// The engine loop has stopped and capture has been torn down.
  stopped,

  /// A fatal error in `message`; the engine has stopped.
  error,

  /// Phase 2: a countdown timer started on the device. `timer_id`,
  /// `timer_label`, and `timer_remaining_secs` (the full duration) are populated;
  /// the UI shows a countdown from that deadline.
  timerStarted,

  /// Phase 2: a countdown timer reached zero (the alarm is sounding). `timer_id`
  /// and `timer_label` identify it.
  timerFinished,

  /// Phase 2: a running timer was cancelled. `timer_id` identifies it.
  timerCancelled,

  /// Recipe mode: the orchestrator pushed a parsed recipe to show on the display's
  /// 3-tab recipe screen. `recipe_json` carries the recipe as a JSON string (title,
  /// summary, source_url, image_url, servings, total_time, ingredients[], steps[])
  /// which the UI parses into the Overview / Ingredients / Steps tabs.
  showRecipe,

  /// Recipe mode: dismiss the recipe screen and return to the idle/ambient display.
  dismissRecipe,

  /// Phase 5: the camera proximity sensor's present/absent state changed. `present`
  /// is `true` when someone has approached the display (brighten) and `false` when
  /// the room has been quiet long enough to dim again (Plan.MD §5). Emitted only on
  /// transitions, never per frame.
  presence,
}
