// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEngineInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -926112597;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_ambient_display',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiSettingsClearMemories({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<bool> crateApiSettingsDeleteMemory({
    required String orchestratorKey,
    required PlatformInt64 id,
    required BigInt discoveryTimeoutSecs,
  });

  Future<bool> crateApiSettingsDeleteSpeaker({
    required String orchestratorKey,
    required String id,
    required BigInt discoveryTimeoutSecs,
  });

  String crateApiEngineEngineGreeting({required String name});

  String crateApiEngineEngineVersion();

  Future<OrchestratorSettings> crateApiSettingsFetchOrchestratorSettings({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<DriveToken> crateApiSettingsGetDriveToken({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<void> crateApiEngineInitApp();

  bool crateApiEngineIsWakeWordEngineRunning();

  Future<List<MemoryEntry>> crateApiSettingsListMemories({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<List<ModelInfo>> crateApiSettingsListModels({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<List<OrchestratorInfo>> crateApiSettingsListOrchestrators({
    required BigInt discoveryTimeoutSecs,
  });

  Future<List<SpeakerInfo>> crateApiSettingsListSpeakers({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<List<VoiceInfo>> crateApiSettingsListVoices({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  });

  Future<bool> crateApiSettingsMergeSpeakers({
    required String orchestratorKey,
    required String keep,
    required String drop,
    required BigInt discoveryTimeoutSecs,
  });

  Future<bool> crateApiSettingsNameSpeaker({
    required String orchestratorKey,
    required String id,
    required String name,
    required BigInt discoveryTimeoutSecs,
  });

  Stream<NotifyEvent> crateApiEngineStartNotifyChannel({
    required NotifyConfig config,
  });

  Stream<WakeWordEvent> crateApiEngineStartWakeWordEngine({
    required WakeWordConfig config,
  });

  Future<void> crateApiEngineStopNotifyChannel();

  Future<void> crateApiEngineStopWakeWordEngine();

  Future<OrchestratorSettings> crateApiSettingsUpdateOrchestratorSettings({
    required String orchestratorKey,
    required SettingsUpdate update,
    required BigInt discoveryTimeoutSecs,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiSettingsClearMemories({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsClearMemoriesConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsClearMemoriesConstMeta =>
      const TaskConstMeta(
        debugName: "clear_memories",
        argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
      );

  @override
  Future<bool> crateApiSettingsDeleteMemory({
    required String orchestratorKey,
    required PlatformInt64 id,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_i_64(id, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsDeleteMemoryConstMeta,
        argValues: [orchestratorKey, id, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsDeleteMemoryConstMeta =>
      const TaskConstMeta(
        debugName: "delete_memory",
        argNames: ["orchestratorKey", "id", "discoveryTimeoutSecs"],
      );

  @override
  Future<bool> crateApiSettingsDeleteSpeaker({
    required String orchestratorKey,
    required String id,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_String(id, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsDeleteSpeakerConstMeta,
        argValues: [orchestratorKey, id, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsDeleteSpeakerConstMeta =>
      const TaskConstMeta(
        debugName: "delete_speaker",
        argNames: ["orchestratorKey", "id", "discoveryTimeoutSecs"],
      );

  @override
  String crateApiEngineEngineGreeting({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineGreetingConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineGreetingConstMeta =>
      const TaskConstMeta(debugName: "engine_greeting", argNames: ["name"]);

  @override
  String crateApiEngineEngineVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineVersionConstMeta =>
      const TaskConstMeta(debugName: "engine_version", argNames: []);

  @override
  Future<OrchestratorSettings> crateApiSettingsFetchOrchestratorSettings({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_orchestrator_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsFetchOrchestratorSettingsConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsFetchOrchestratorSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_orchestrator_settings",
        argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
      );

  @override
  Future<DriveToken> crateApiSettingsGetDriveToken({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_drive_token,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsGetDriveTokenConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsGetDriveTokenConstMeta =>
      const TaskConstMeta(
        debugName: "get_drive_token",
        argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
      );

  @override
  Future<void> crateApiEngineInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiEngineIsWakeWordEngineRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineIsWakeWordEngineRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineIsWakeWordEngineRunningConstMeta =>
      const TaskConstMeta(
        debugName: "is_wake_word_engine_running",
        argNames: [],
      );

  @override
  Future<List<MemoryEntry>> crateApiSettingsListMemories({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsListMemoriesConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsListMemoriesConstMeta =>
      const TaskConstMeta(
        debugName: "list_memories",
        argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
      );

  @override
  Future<List<ModelInfo>> crateApiSettingsListModels({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_model_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsListModelsConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsListModelsConstMeta => const TaskConstMeta(
    debugName: "list_models",
    argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
  );

  @override
  Future<List<OrchestratorInfo>> crateApiSettingsListOrchestrators({
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_orchestrator_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsListOrchestratorsConstMeta,
        argValues: [discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsListOrchestratorsConstMeta =>
      const TaskConstMeta(
        debugName: "list_orchestrators",
        argNames: ["discoveryTimeoutSecs"],
      );

  @override
  Future<List<SpeakerInfo>> crateApiSettingsListSpeakers({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_speaker_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsListSpeakersConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsListSpeakersConstMeta =>
      const TaskConstMeta(
        debugName: "list_speakers",
        argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
      );

  @override
  Future<List<VoiceInfo>> crateApiSettingsListVoices({
    required String orchestratorKey,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_voice_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsListVoicesConstMeta,
        argValues: [orchestratorKey, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsListVoicesConstMeta => const TaskConstMeta(
    debugName: "list_voices",
    argNames: ["orchestratorKey", "discoveryTimeoutSecs"],
  );

  @override
  Future<bool> crateApiSettingsMergeSpeakers({
    required String orchestratorKey,
    required String keep,
    required String drop,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_String(keep, serializer);
          sse_encode_String(drop, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsMergeSpeakersConstMeta,
        argValues: [orchestratorKey, keep, drop, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsMergeSpeakersConstMeta =>
      const TaskConstMeta(
        debugName: "merge_speakers",
        argNames: ["orchestratorKey", "keep", "drop", "discoveryTimeoutSecs"],
      );

  @override
  Future<bool> crateApiSettingsNameSpeaker({
    required String orchestratorKey,
    required String id,
    required String name,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsNameSpeakerConstMeta,
        argValues: [orchestratorKey, id, name, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsNameSpeakerConstMeta =>
      const TaskConstMeta(
        debugName: "name_speaker",
        argNames: ["orchestratorKey", "id", "name", "discoveryTimeoutSecs"],
      );

  @override
  Stream<NotifyEvent> crateApiEngineStartNotifyChannel({
    required NotifyConfig config,
  }) {
    final sink = RustStreamSink<NotifyEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_notify_config(config, serializer);
            sse_encode_StreamSink_notify_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineStartNotifyChannelConstMeta,
          argValues: [config, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineStartNotifyChannelConstMeta =>
      const TaskConstMeta(
        debugName: "start_notify_channel",
        argNames: ["config", "sink"],
      );

  @override
  Stream<WakeWordEvent> crateApiEngineStartWakeWordEngine({
    required WakeWordConfig config,
  }) {
    final sink = RustStreamSink<WakeWordEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_wake_word_config(config, serializer);
            sse_encode_StreamSink_wake_word_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEngineStartWakeWordEngineConstMeta,
          argValues: [config, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEngineStartWakeWordEngineConstMeta =>
      const TaskConstMeta(
        debugName: "start_wake_word_engine",
        argNames: ["config", "sink"],
      );

  @override
  Future<void> crateApiEngineStopNotifyChannel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineStopNotifyChannelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineStopNotifyChannelConstMeta =>
      const TaskConstMeta(debugName: "stop_notify_channel", argNames: []);

  @override
  Future<void> crateApiEngineStopWakeWordEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineStopWakeWordEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineStopWakeWordEngineConstMeta =>
      const TaskConstMeta(debugName: "stop_wake_word_engine", argNames: []);

  @override
  Future<OrchestratorSettings> crateApiSettingsUpdateOrchestratorSettings({
    required String orchestratorKey,
    required SettingsUpdate update,
    required BigInt discoveryTimeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(orchestratorKey, serializer);
          sse_encode_box_autoadd_settings_update(update, serializer);
          sse_encode_u_64(discoveryTimeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_orchestrator_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsUpdateOrchestratorSettingsConstMeta,
        argValues: [orchestratorKey, update, discoveryTimeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsUpdateOrchestratorSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "update_orchestrator_settings",
        argNames: ["orchestratorKey", "update", "discoveryTimeoutSecs"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NotifyEvent> dco_decode_StreamSink_notify_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<WakeWordEvent> dco_decode_StreamSink_wake_word_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  NotifyConfig dco_decode_box_autoadd_notify_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_notify_config(raw);
  }

  @protected
  SettingsUpdate dco_decode_box_autoadd_settings_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings_update(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  WakeWordConfig dco_decode_box_autoadd_wake_word_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wake_word_config(raw);
  }

  @protected
  DriveToken dco_decode_drive_token(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DriveToken(
      linked: dco_decode_bool(arr[0]),
      configured: dco_decode_bool(arr[1]),
      clientId: dco_decode_String(arr[2]),
      clientSecret: dco_decode_String(arr[3]),
      refreshToken: dco_decode_String(arr[4]),
      folderIds: dco_decode_list_String(arr[5]),
      scope: dco_decode_String(arr[6]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MemoryEntry> dco_decode_list_memory_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_memory_entry).toList();
  }

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_info).toList();
  }

  @protected
  List<OrchestratorInfo> dco_decode_list_orchestrator_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_orchestrator_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SpeakerInfo> dco_decode_list_speaker_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_speaker_info).toList();
  }

  @protected
  List<VoiceInfo> dco_decode_list_voice_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_voice_info).toList();
  }

  @protected
  MemoryEntry dco_decode_memory_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MemoryEntry(
      id: dco_decode_i_64(arr[0]),
      kind: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      source: dco_decode_String(arr[3]),
      createdAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  ModelInfo dco_decode_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ModelInfo(
      provider: dco_decode_String(arr[0]),
      id: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
    );
  }

  @protected
  NotifyConfig dco_decode_notify_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NotifyConfig(
      orchestratorKey: dco_decode_String(arr[0]),
      discoveryTimeoutSecs: dco_decode_u_64(arr[1]),
      deviceId: dco_decode_String(arr[2]),
    );
  }

  @protected
  NotifyEvent dco_decode_notify_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NotifyEvent(
      id: dco_decode_String(arr[0]),
      priority: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  OrchestratorInfo dco_decode_orchestrator_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OrchestratorInfo(
      key: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
    );
  }

  @protected
  OrchestratorSettings dco_decode_orchestrator_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return OrchestratorSettings(
      ok: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      llmBackend: dco_decode_String(arr[2]),
      llmModel: dco_decode_opt_String(arr[3]),
      anthropicAuth: dco_decode_String(arr[4]),
      ttsVoice: dco_decode_opt_String(arr[5]),
      endSilenceMs: dco_decode_u_32(arr[6]),
      voiceRmsThreshold: dco_decode_f_64(arr[7]),
    );
  }

  @protected
  SettingsUpdate dco_decode_settings_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SettingsUpdate(
      llmBackend: dco_decode_opt_String(arr[0]),
      llmModel: dco_decode_opt_String(arr[1]),
      anthropicAuth: dco_decode_opt_String(arr[2]),
      setTtsVoice: dco_decode_bool(arr[3]),
      ttsVoice: dco_decode_opt_String(arr[4]),
      endSilenceMs: dco_decode_opt_box_autoadd_u_32(arr[5]),
      voiceRmsThreshold: dco_decode_opt_box_autoadd_f_64(arr[6]),
    );
  }

  @protected
  SpeakerInfo dco_decode_speaker_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SpeakerInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      labeled: dco_decode_bool(arr[2]),
      samples: dco_decode_i_64(arr[3]),
      createdAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VoiceInfo dco_decode_voice_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VoiceInfo(
      name: dco_decode_String(arr[0]),
      language: dco_decode_opt_String(arr[1]),
      label: dco_decode_String(arr[2]),
    );
  }

  @protected
  WakeWordConfig dco_decode_wake_word_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 20)
      throw Exception('unexpected arr length: expect 20 but see ${arr.length}');
    return WakeWordConfig(
      melspecModelPath: dco_decode_String(arr[0]),
      embeddingModelPath: dco_decode_String(arr[1]),
      wakewordModelPath: dco_decode_String(arr[2]),
      modelName: dco_decode_String(arr[3]),
      threshold: dco_decode_f_32(arr[4]),
      activeThreshold: dco_decode_f_32(arr[5]),
      discoveryTimeoutSecs: dco_decode_u_64(arr[6]),
      orchestratorKey: dco_decode_String(arr[7]),
      turnTimeoutSecs: dco_decode_u_64(arr[8]),
      smoothingWindow: dco_decode_u_32(arr[9]),
      fireOnPeak: dco_decode_bool(arr[10]),
      playbackBufferSecs: dco_decode_u_32(arr[11]),
      useAudiorecord: dco_decode_bool(arr[12]),
      micSource: dco_decode_u_32(arr[13]),
      platformAec: dco_decode_bool(arr[14]),
      platformAgc: dco_decode_bool(arr[15]),
      platformNs: dco_decode_bool(arr[16]),
      cameraProximity: dco_decode_bool(arr[17]),
      proximityMotionThreshold: dco_decode_f_32(arr[18]),
      proximityReleaseSecs: dco_decode_u_32(arr[19]),
    );
  }

  @protected
  WakeWordEvent dco_decode_wake_word_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return WakeWordEvent(
      kind: dco_decode_wake_word_event_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      device: dco_decode_String(arr[2]),
      deviceSampleRate: dco_decode_u_32(arr[3]),
      channels: dco_decode_u_16(arr[4]),
      rms: dco_decode_f_32(arr[5]),
      score: dco_decode_f_32(arr[6]),
      model: dco_decode_String(arr[7]),
      transcript: dco_decode_String(arr[8]),
      reply: dco_decode_String(arr[9]),
      timerId: dco_decode_u_32(arr[10]),
      timerLabel: dco_decode_String(arr[11]),
      timerRemainingSecs: dco_decode_u_32(arr[12]),
      present: dco_decode_bool(arr[13]),
    );
  }

  @protected
  WakeWordEventKind dco_decode_wake_word_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WakeWordEventKind.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NotifyEvent> sse_decode_StreamSink_notify_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<WakeWordEvent> sse_decode_StreamSink_wake_word_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  NotifyConfig sse_decode_box_autoadd_notify_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_notify_config(deserializer));
  }

  @protected
  SettingsUpdate sse_decode_box_autoadd_settings_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings_update(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  WakeWordConfig sse_decode_box_autoadd_wake_word_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wake_word_config(deserializer));
  }

  @protected
  DriveToken sse_decode_drive_token(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_linked = sse_decode_bool(deserializer);
    var var_configured = sse_decode_bool(deserializer);
    var var_clientId = sse_decode_String(deserializer);
    var var_clientSecret = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    var var_folderIds = sse_decode_list_String(deserializer);
    var var_scope = sse_decode_String(deserializer);
    return DriveToken(
      linked: var_linked,
      configured: var_configured,
      clientId: var_clientId,
      clientSecret: var_clientSecret,
      refreshToken: var_refreshToken,
      folderIds: var_folderIds,
      scope: var_scope,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemoryEntry> sse_decode_list_memory_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_memory_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<OrchestratorInfo> sse_decode_list_orchestrator_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OrchestratorInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_orchestrator_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SpeakerInfo> sse_decode_list_speaker_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SpeakerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_speaker_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<VoiceInfo> sse_decode_list_voice_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VoiceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_voice_info(deserializer));
    }
    return ans_;
  }

  @protected
  MemoryEntry sse_decode_memory_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return MemoryEntry(
      id: var_id,
      kind: var_kind,
      content: var_content,
      source: var_source,
      createdAt: var_createdAt,
    );
  }

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    return ModelInfo(provider: var_provider, id: var_id, label: var_label);
  }

  @protected
  NotifyConfig sse_decode_notify_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_orchestratorKey = sse_decode_String(deserializer);
    var var_discoveryTimeoutSecs = sse_decode_u_64(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    return NotifyConfig(
      orchestratorKey: var_orchestratorKey,
      discoveryTimeoutSecs: var_discoveryTimeoutSecs,
      deviceId: var_deviceId,
    );
  }

  @protected
  NotifyEvent sse_decode_notify_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_priority = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    return NotifyEvent(
      id: var_id,
      priority: var_priority,
      title: var_title,
      body: var_body,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrchestratorInfo sse_decode_orchestrator_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    return OrchestratorInfo(
      key: var_key,
      name: var_name,
      host: var_host,
      port: var_port,
    );
  }

  @protected
  OrchestratorSettings sse_decode_orchestrator_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_llmBackend = sse_decode_String(deserializer);
    var var_llmModel = sse_decode_opt_String(deserializer);
    var var_anthropicAuth = sse_decode_String(deserializer);
    var var_ttsVoice = sse_decode_opt_String(deserializer);
    var var_endSilenceMs = sse_decode_u_32(deserializer);
    var var_voiceRmsThreshold = sse_decode_f_64(deserializer);
    return OrchestratorSettings(
      ok: var_ok,
      message: var_message,
      llmBackend: var_llmBackend,
      llmModel: var_llmModel,
      anthropicAuth: var_anthropicAuth,
      ttsVoice: var_ttsVoice,
      endSilenceMs: var_endSilenceMs,
      voiceRmsThreshold: var_voiceRmsThreshold,
    );
  }

  @protected
  SettingsUpdate sse_decode_settings_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_llmBackend = sse_decode_opt_String(deserializer);
    var var_llmModel = sse_decode_opt_String(deserializer);
    var var_anthropicAuth = sse_decode_opt_String(deserializer);
    var var_setTtsVoice = sse_decode_bool(deserializer);
    var var_ttsVoice = sse_decode_opt_String(deserializer);
    var var_endSilenceMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_voiceRmsThreshold = sse_decode_opt_box_autoadd_f_64(deserializer);
    return SettingsUpdate(
      llmBackend: var_llmBackend,
      llmModel: var_llmModel,
      anthropicAuth: var_anthropicAuth,
      setTtsVoice: var_setTtsVoice,
      ttsVoice: var_ttsVoice,
      endSilenceMs: var_endSilenceMs,
      voiceRmsThreshold: var_voiceRmsThreshold,
    );
  }

  @protected
  SpeakerInfo sse_decode_speaker_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_labeled = sse_decode_bool(deserializer);
    var var_samples = sse_decode_i_64(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return SpeakerInfo(
      id: var_id,
      name: var_name,
      labeled: var_labeled,
      samples: var_samples,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VoiceInfo sse_decode_voice_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    return VoiceInfo(name: var_name, language: var_language, label: var_label);
  }

  @protected
  WakeWordConfig sse_decode_wake_word_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_melspecModelPath = sse_decode_String(deserializer);
    var var_embeddingModelPath = sse_decode_String(deserializer);
    var var_wakewordModelPath = sse_decode_String(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    var var_threshold = sse_decode_f_32(deserializer);
    var var_activeThreshold = sse_decode_f_32(deserializer);
    var var_discoveryTimeoutSecs = sse_decode_u_64(deserializer);
    var var_orchestratorKey = sse_decode_String(deserializer);
    var var_turnTimeoutSecs = sse_decode_u_64(deserializer);
    var var_smoothingWindow = sse_decode_u_32(deserializer);
    var var_fireOnPeak = sse_decode_bool(deserializer);
    var var_playbackBufferSecs = sse_decode_u_32(deserializer);
    var var_useAudiorecord = sse_decode_bool(deserializer);
    var var_micSource = sse_decode_u_32(deserializer);
    var var_platformAec = sse_decode_bool(deserializer);
    var var_platformAgc = sse_decode_bool(deserializer);
    var var_platformNs = sse_decode_bool(deserializer);
    var var_cameraProximity = sse_decode_bool(deserializer);
    var var_proximityMotionThreshold = sse_decode_f_32(deserializer);
    var var_proximityReleaseSecs = sse_decode_u_32(deserializer);
    return WakeWordConfig(
      melspecModelPath: var_melspecModelPath,
      embeddingModelPath: var_embeddingModelPath,
      wakewordModelPath: var_wakewordModelPath,
      modelName: var_modelName,
      threshold: var_threshold,
      activeThreshold: var_activeThreshold,
      discoveryTimeoutSecs: var_discoveryTimeoutSecs,
      orchestratorKey: var_orchestratorKey,
      turnTimeoutSecs: var_turnTimeoutSecs,
      smoothingWindow: var_smoothingWindow,
      fireOnPeak: var_fireOnPeak,
      playbackBufferSecs: var_playbackBufferSecs,
      useAudiorecord: var_useAudiorecord,
      micSource: var_micSource,
      platformAec: var_platformAec,
      platformAgc: var_platformAgc,
      platformNs: var_platformNs,
      cameraProximity: var_cameraProximity,
      proximityMotionThreshold: var_proximityMotionThreshold,
      proximityReleaseSecs: var_proximityReleaseSecs,
    );
  }

  @protected
  WakeWordEvent sse_decode_wake_word_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_wake_word_event_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_device = sse_decode_String(deserializer);
    var var_deviceSampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_rms = sse_decode_f_32(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_transcript = sse_decode_String(deserializer);
    var var_reply = sse_decode_String(deserializer);
    var var_timerId = sse_decode_u_32(deserializer);
    var var_timerLabel = sse_decode_String(deserializer);
    var var_timerRemainingSecs = sse_decode_u_32(deserializer);
    var var_present = sse_decode_bool(deserializer);
    return WakeWordEvent(
      kind: var_kind,
      message: var_message,
      device: var_device,
      deviceSampleRate: var_deviceSampleRate,
      channels: var_channels,
      rms: var_rms,
      score: var_score,
      model: var_model,
      transcript: var_transcript,
      reply: var_reply,
      timerId: var_timerId,
      timerLabel: var_timerLabel,
      timerRemainingSecs: var_timerRemainingSecs,
      present: var_present,
    );
  }

  @protected
  WakeWordEventKind sse_decode_wake_word_event_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WakeWordEventKind.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_notify_event_Sse(
    RustStreamSink<NotifyEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_notify_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_wake_word_event_Sse(
    RustStreamSink<WakeWordEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_wake_word_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_notify_config(
    NotifyConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_notify_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings_update(
    SettingsUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings_update(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_wake_word_config(
    WakeWordConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wake_word_config(self, serializer);
  }

  @protected
  void sse_encode_drive_token(DriveToken self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.linked, serializer);
    sse_encode_bool(self.configured, serializer);
    sse_encode_String(self.clientId, serializer);
    sse_encode_String(self.clientSecret, serializer);
    sse_encode_String(self.refreshToken, serializer);
    sse_encode_list_String(self.folderIds, serializer);
    sse_encode_String(self.scope, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_memory_entry(
    List<MemoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_memory_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_orchestrator_info(
    List<OrchestratorInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_orchestrator_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_speaker_info(
    List<SpeakerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_speaker_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_voice_info(
    List<VoiceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_voice_info(item, serializer);
    }
  }

  @protected
  void sse_encode_memory_entry(MemoryEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_notify_config(NotifyConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.orchestratorKey, serializer);
    sse_encode_u_64(self.discoveryTimeoutSecs, serializer);
    sse_encode_String(self.deviceId, serializer);
  }

  @protected
  void sse_encode_notify_event(NotifyEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.priority, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_orchestrator_info(
    OrchestratorInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_orchestrator_settings(
    OrchestratorSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.llmBackend, serializer);
    sse_encode_opt_String(self.llmModel, serializer);
    sse_encode_String(self.anthropicAuth, serializer);
    sse_encode_opt_String(self.ttsVoice, serializer);
    sse_encode_u_32(self.endSilenceMs, serializer);
    sse_encode_f_64(self.voiceRmsThreshold, serializer);
  }

  @protected
  void sse_encode_settings_update(
    SettingsUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.llmBackend, serializer);
    sse_encode_opt_String(self.llmModel, serializer);
    sse_encode_opt_String(self.anthropicAuth, serializer);
    sse_encode_bool(self.setTtsVoice, serializer);
    sse_encode_opt_String(self.ttsVoice, serializer);
    sse_encode_opt_box_autoadd_u_32(self.endSilenceMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.voiceRmsThreshold, serializer);
  }

  @protected
  void sse_encode_speaker_info(SpeakerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_bool(self.labeled, serializer);
    sse_encode_i_64(self.samples, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_voice_info(VoiceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_wake_word_config(
    WakeWordConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.melspecModelPath, serializer);
    sse_encode_String(self.embeddingModelPath, serializer);
    sse_encode_String(self.wakewordModelPath, serializer);
    sse_encode_String(self.modelName, serializer);
    sse_encode_f_32(self.threshold, serializer);
    sse_encode_f_32(self.activeThreshold, serializer);
    sse_encode_u_64(self.discoveryTimeoutSecs, serializer);
    sse_encode_String(self.orchestratorKey, serializer);
    sse_encode_u_64(self.turnTimeoutSecs, serializer);
    sse_encode_u_32(self.smoothingWindow, serializer);
    sse_encode_bool(self.fireOnPeak, serializer);
    sse_encode_u_32(self.playbackBufferSecs, serializer);
    sse_encode_bool(self.useAudiorecord, serializer);
    sse_encode_u_32(self.micSource, serializer);
    sse_encode_bool(self.platformAec, serializer);
    sse_encode_bool(self.platformAgc, serializer);
    sse_encode_bool(self.platformNs, serializer);
    sse_encode_bool(self.cameraProximity, serializer);
    sse_encode_f_32(self.proximityMotionThreshold, serializer);
    sse_encode_u_32(self.proximityReleaseSecs, serializer);
  }

  @protected
  void sse_encode_wake_word_event(
    WakeWordEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wake_word_event_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.device, serializer);
    sse_encode_u_32(self.deviceSampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_f_32(self.rms, serializer);
    sse_encode_f_32(self.score, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.transcript, serializer);
    sse_encode_String(self.reply, serializer);
    sse_encode_u_32(self.timerId, serializer);
    sse_encode_String(self.timerLabel, serializer);
    sse_encode_u_32(self.timerRemainingSecs, serializer);
    sse_encode_bool(self.present, serializer);
  }

  @protected
  void sse_encode_wake_word_event_kind(
    WakeWordEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
