// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/engine.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<NotifyEvent> dco_decode_StreamSink_notify_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<WakeWordEvent> dco_decode_StreamSink_wake_word_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  NotifyConfig dco_decode_box_autoadd_notify_config(dynamic raw);

  @protected
  SettingsUpdate dco_decode_box_autoadd_settings_update(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WakeWordConfig dco_decode_box_autoadd_wake_word_config(dynamic raw);

  @protected
  DriveToken dco_decode_drive_token(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MemoryEntry> dco_decode_list_memory_entry(dynamic raw);

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw);

  @protected
  List<OrchestratorInfo> dco_decode_list_orchestrator_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SpeakerInfo> dco_decode_list_speaker_info(dynamic raw);

  @protected
  List<VoiceInfo> dco_decode_list_voice_info(dynamic raw);

  @protected
  MemoryEntry dco_decode_memory_entry(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  NotifyConfig dco_decode_notify_config(dynamic raw);

  @protected
  NotifyEvent dco_decode_notify_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  OrchestratorInfo dco_decode_orchestrator_info(dynamic raw);

  @protected
  OrchestratorSettings dco_decode_orchestrator_settings(dynamic raw);

  @protected
  SettingsUpdate dco_decode_settings_update(dynamic raw);

  @protected
  SpeakerInfo dco_decode_speaker_info(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VoiceInfo dco_decode_voice_info(dynamic raw);

  @protected
  WakeWordConfig dco_decode_wake_word_config(dynamic raw);

  @protected
  WakeWordEvent dco_decode_wake_word_event(dynamic raw);

  @protected
  WakeWordEventKind dco_decode_wake_word_event_kind(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<NotifyEvent> sse_decode_StreamSink_notify_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WakeWordEvent> sse_decode_StreamSink_wake_word_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  NotifyConfig sse_decode_box_autoadd_notify_config(
    SseDeserializer deserializer,
  );

  @protected
  SettingsUpdate sse_decode_box_autoadd_settings_update(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WakeWordConfig sse_decode_box_autoadd_wake_word_config(
    SseDeserializer deserializer,
  );

  @protected
  DriveToken sse_decode_drive_token(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MemoryEntry> sse_decode_list_memory_entry(SseDeserializer deserializer);

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer);

  @protected
  List<OrchestratorInfo> sse_decode_list_orchestrator_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SpeakerInfo> sse_decode_list_speaker_info(SseDeserializer deserializer);

  @protected
  List<VoiceInfo> sse_decode_list_voice_info(SseDeserializer deserializer);

  @protected
  MemoryEntry sse_decode_memory_entry(SseDeserializer deserializer);

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  NotifyConfig sse_decode_notify_config(SseDeserializer deserializer);

  @protected
  NotifyEvent sse_decode_notify_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  OrchestratorInfo sse_decode_orchestrator_info(SseDeserializer deserializer);

  @protected
  OrchestratorSettings sse_decode_orchestrator_settings(
    SseDeserializer deserializer,
  );

  @protected
  SettingsUpdate sse_decode_settings_update(SseDeserializer deserializer);

  @protected
  SpeakerInfo sse_decode_speaker_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VoiceInfo sse_decode_voice_info(SseDeserializer deserializer);

  @protected
  WakeWordConfig sse_decode_wake_word_config(SseDeserializer deserializer);

  @protected
  WakeWordEvent sse_decode_wake_word_event(SseDeserializer deserializer);

  @protected
  WakeWordEventKind sse_decode_wake_word_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_notify_event_Sse(
    RustStreamSink<NotifyEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_wake_word_event_Sse(
    RustStreamSink<WakeWordEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_notify_config(
    NotifyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_update(
    SettingsUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wake_word_config(
    WakeWordConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_drive_token(DriveToken self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_memory_entry(
    List<MemoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_orchestrator_info(
    List<OrchestratorInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_speaker_info(
    List<SpeakerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_voice_info(
    List<VoiceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_entry(MemoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_notify_config(NotifyConfig self, SseSerializer serializer);

  @protected
  void sse_encode_notify_event(NotifyEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_orchestrator_info(
    OrchestratorInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_orchestrator_settings(
    OrchestratorSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_update(
    SettingsUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_speaker_info(SpeakerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_voice_info(VoiceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_wake_word_config(
    WakeWordConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wake_word_event(WakeWordEvent self, SseSerializer serializer);

  @protected
  void sse_encode_wake_word_event_kind(
    WakeWordEventKind self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
