// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base`, `connecting`, `detected`, `disconnected`, `dismiss_place`, `dismiss_recipe`, `dismiss_weather`, `engine_target`, `error`, `font_adjust`, `level_diag`, `level`, `listening_followup`, `notify_slot`, `presence`, `recipe_navigate`, `recipe_scroll`, `reply_token`, `show_place`, `show_recipe`, `show_weather`, `speaking_done`, `speaking`, `started`, `status`, `stopped`, `streaming`, `timer_cancelled`, `timer_finished`, `timer_started`, `transcript`, `weather_current`, `weather_slot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NotifyHandle`, `WeatherHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

/// A friendly greeting from the native Rust engine.
///
/// The Flutter UI calls this on startup to confirm the cross-compiled shared
/// library loaded and the FRB bridge is live on the device.
String engineGreeting({required String name}) =>
    RustLib.instance.api.crateApiEngineEngineGreeting(name: name);

/// A stable per-device hardware id derived from the primary network interface's MAC
/// address, formatted `anamanti-<12 lowercase hex>` (colons stripped) — e.g.
/// `anamanti-140ac5942aca`. Reading the MAC from `/sys/class/net/<iface>/address`
/// guarantees uniqueness across devices without any build-time configuration.
///
/// Returns an empty string if no usable MAC is found (an unreadable file, or an
/// all-zero / locked-down `02:00:00:00:00:00` placeholder); the Dart layer then
/// falls back to a persisted random id so the device still has a stable identity.
String deviceHardwareId() =>
    RustLib.instance.api.crateApiEngineDeviceHardwareId();

/// Reports the native engine's version and build target so the device can show
/// exactly which cross-compiled binary it is running.
String engineVersion() => RustLib.instance.api.crateApiEngineEngineVersion();

/// Start microphone capture and continuous on-device wake-word scoring, pushing
/// [`WakeWordEvent`]s to Dart. Replaces any engine already running.
Stream<WakeWordEvent> startWakeWordEngine({required WakeWordConfig config}) =>
    RustLib.instance.api.crateApiEngineStartWakeWordEngine(config: config);

/// Stop the wake-word engine and release the microphone. Idempotent.
Future<void> stopWakeWordEngine() =>
    RustLib.instance.api.crateApiEngineStopWakeWordEngine();

/// Whether the wake-word engine is currently running.
bool isWakeWordEngineRunning() =>
    RustLib.instance.api.crateApiEngineIsWakeWordEngineRunning();

/// Live-adjust the capture gain (dB) and idle wake-word detection threshold on the
/// **running** engine without restarting it, so the audio-diagnostics screen's
/// sliders take effect instantly while the user watches the meters. The engine
/// re-reads both values each audio block. They are re-seeded from [`WakeWordConfig`]
/// on the next engine start, so persist the chosen values to settings to keep them
/// across restarts. A harmless no-op when no engine is running. `gain_db` is clamped
/// to `[0, 36]`; `threshold` to `[0, 1]`.
void updateDiagnosticsTuning({
  required double gainDb,
  required double threshold,
}) => RustLib.instance.api.crateApiEngineUpdateDiagnosticsTuning(
  gainDb: gainDb,
  threshold: threshold,
);

/// Register user activity that isn't camera motion — a voice turn or a screen touch
/// — so it resets the screen-dim countdown (and brightens the screen if it had
/// already dimmed). Flutter calls this on each voice-turn transition and on screen
/// touches. Safe to call any time: it's a no-op when camera proximity isn't running,
/// and a harmless no-op off Android (host tests, no camera).
void noteUserActivity() =>
    RustLib.instance.api.crateApiEngineNoteUserActivity();

/// Report the recipe screen's state as the device's **display context** so the next
/// voice turn's `audio-start` carries it to the orchestrator, letting the LLM know a
/// recipe is up (and which tab / scroll position) so it can drive the screen by voice
/// (switch tabs, scroll, close).
///
/// This is the recipe screen's setter for the general display-context mechanism (see
/// [`crate::engine::set_display_context`]); other voice-controllable screens — music,
/// weather, photos — would add their own `set_<screen>_context` entry that builds the
/// matching `screen` block (`{kind, <kind>:{...}}`).
///
/// Flutter calls this when recipe mode opens or closes and whenever the active tab or a
/// pane's scroll position changes. `active == false` clears the context (idle screen);
/// the other fields are ignored. `tab` is `"overview"` / `"ingredients"` / `"steps"`.
void setRecipeContext({
  required bool active,
  required String title,
  required String tab,
  required bool atTop,
  required bool atBottom,
  required int ingredientCount,
  required int stepCount,
}) => RustLib.instance.api.crateApiEngineSetRecipeContext(
  active: active,
  title: title,
  tab: tab,
  atTop: atTop,
  atBottom: atBottom,
  ingredientCount: ingredientCount,
  stepCount: stepCount,
);

/// Report the weather screen's state as the device's **display context** so the next
/// voice turn's `audio-start` carries it to the orchestrator, letting the LLM know the
/// forecast is up (and what it shows) so it can answer follow-ups in context or close it
/// on request. The weather screen's setter for the general display-context mechanism (see
/// [`set_recipe_context`] / [`crate::engine::set_display_context`]).
///
/// Flutter calls this when the full-screen weather view opens or closes. `active == false`
/// clears the context (idle screen); the other fields are ignored. The small clock chip
/// (the ambient indicator) is **not** a screen and never sets display context.
void setWeatherContext({
  required bool active,
  required String location,
  required String units,
  required int temp,
  required String description,
}) => RustLib.instance.api.crateApiEngineSetWeatherContext(
  active: active,
  location: location,
  units: units,
  temp: temp,
  description: description,
);

/// Report the place card's state as the device's **display context** so the next voice
/// turn's `audio-start` carries it to the orchestrator, letting the LLM know a place card
/// is up (and which place) so it can answer follow-ups in context or close it on request.
/// The place card's setter for the general display-context mechanism (see
/// [`set_weather_context`] / [`crate::engine::set_display_context`]).
///
/// Flutter calls this when the place card opens or closes. `active == false` clears the
/// context (idle screen); the other fields are ignored.
void setPlaceContext({
  required bool active,
  required String name,
  required String address,
}) => RustLib.instance.api.crateApiEngineSetPlaceContext(
  active: active,
  name: name,
  address: address,
);

/// Report the device's **font-scaling context** so the next voice turn's `audio-start`
/// carries it to the orchestrator as the `screen.font` sibling (orthogonal to the
/// foreground widget, like `screen.timers`). Lets "increase font" / "decrease font"
/// resolve only when a resizable surface is on screen (`scalable`), and lets the assistant
/// say when the text is already at the maximum/minimum. `scale` is the current global
/// multiplier (1.0 = unscaled). Flutter calls this at startup and after each adjustment.
void setFontContext({
  required bool scalable,
  required double scale,
  required bool atMin,
  required bool atMax,
}) => RustLib.instance.api.crateApiEngineSetFontContext(
  scalable: scalable,
  scale: scale,
  atMin: atMin,
  atMax: atMax,
);

/// Open the persistent proactive-notification channel and stream pushed
/// notifications to Dart. Replaces any channel already running (so it can be
/// restarted when the pinned orchestrator changes). The channel dials the pinned
/// orchestrator and reconnects with backoff for the life of the subscription.
Stream<NotifyEvent> startNotifyChannel({required NotifyConfig config}) =>
    RustLib.instance.api.crateApiEngineStartNotifyChannel(config: config);

/// Stop the proactive-notification channel (if any) and join its thread. Idempotent.
Future<void> stopNotifyChannel() =>
    RustLib.instance.api.crateApiEngineStopNotifyChannel();

/// Open the persistent ambient-weather channel and stream pushed reports to Dart.
/// Replaces any channel already running (so it can be restarted when the pinned
/// orchestrator changes). Dials the pinned orchestrator and reconnects with backoff
/// for the life of the subscription.
Stream<WeatherPush> startWeatherChannel({required WeatherConfig config}) =>
    RustLib.instance.api.crateApiEngineStartWeatherChannel(config: config);

/// Stop the ambient-weather channel (if any) and join its thread. Idempotent.
Future<void> stopWeatherChannel() =>
    RustLib.instance.api.crateApiEngineStopWeatherChannel();

/// Config for the persistent notify channel. The orchestrator is discovered over
/// mDNS at connect time (same as the voice path), so only the pin, the browse
/// timeout, and this display's id are configured here.
class NotifyConfig {
  /// Stable selection key (`instance_id` TXT) of the pinned orchestrator; empty =
  /// "Auto" (first available). Mirrors [`WakeWordConfig::orchestrator_key`] so the
  /// notify channel targets the same Mac the voice path does.
  final String orchestratorKey;

  /// Seconds to browse `_wyoming._tcp` before falling back to the cached host
  /// (0 = built-in default).
  final BigInt discoveryTimeoutSecs;

  /// A stable identifier for this display, sent in the `anamanti-hello` frame so the
  /// orchestrator can key notifications per device (may be empty).
  final String deviceId;

  /// A human-friendly label for this display (e.g. "Kitchen"), sent alongside
  /// `device_id` in the `anamanti-hello` frame so the Core can name it (may be empty).
  final String deviceName;

  const NotifyConfig({
    required this.orchestratorKey,
    required this.discoveryTimeoutSecs,
    required this.deviceId,
    required this.deviceName,
  });

  @override
  int get hashCode =>
      orchestratorKey.hashCode ^
      discoveryTimeoutSecs.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotifyConfig &&
          runtimeType == other.runtimeType &&
          orchestratorKey == other.orchestratorKey &&
          discoveryTimeoutSecs == other.discoveryTimeoutSecs &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName;
}

/// One proactive notification pushed from the orchestrator, streamed to Flutter.
/// Modeled as a flat struct (like [`WakeWordEvent`]) so the FRB boundary stays
/// dependency-free.
class NotifyEvent {
  /// Stable notification id (for dedup / dismiss on the UI side).
  final String id;

  /// `"info"` | `"reminder"` | `"alert"` — drives the banner styling.
  final String priority;

  /// Short headline.
  final String title;

  /// Body text.
  final String body;

  const NotifyEvent({
    required this.id,
    required this.priority,
    required this.title,
    required this.body,
  });

  @override
  int get hashCode =>
      id.hashCode ^ priority.hashCode ^ title.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotifyEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          priority == other.priority &&
          title == other.title &&
          body == other.body;
}

/// Paths and tuning for the openWakeWord three-model chain plus the Phase-3
/// Wyoming turn. The Flutter layer resolves the model paths from bundled assets
/// or the settings screen (Phase 6) and hands them to the engine. The Wyoming
/// host itself is discovered over mDNS at turn time, so no address is configured
/// here (architecture.md §5).
class WakeWordConfig {
  /// Path to the melspectrogram ONNX model (`melspectrogram.onnx`).
  final String melspecModelPath;

  /// Path to the shared feature/embedding ONNX model (`embedding_model.onnx`).
  final String embeddingModelPath;

  /// Path to the wake-word classifier ONNX model (e.g. `alexa_v0.1.onnx`).
  final String wakewordModelPath;

  /// Human-readable wake-word name, echoed back on detection events.
  final String modelName;

  /// Confidence in [0, 1] above which a detection is reported while idle.
  final double threshold;

  /// Higher confidence required to fire *while a turn is already active*
  /// (streaming/speaking). This is the AEC-interim mitigation from the locked
  /// decisions: raise the bar during playback so the device's own speaker is
  /// less likely to self-trigger (Plan.MD §4). Set equal to `threshold` to
  /// disable. Clamped to at least `threshold` at runtime.
  final double activeThreshold;

  /// Seconds to browse `_wyoming._tcp` before falling back to the cached host
  /// (0 = use the built-in default).
  final BigInt discoveryTimeoutSecs;

  /// Stable selection key (`instance_id` TXT) of the orchestrator this display
  /// is pinned to. Empty = "Auto" (connect to the first available orchestrator).
  /// When set, discovery resolves *only* this orchestrator and stays offline if
  /// it is unreachable, rather than silently connecting to a different one.
  final String orchestratorKey;

  /// Seconds of server silence before a turn is defensively abandoned
  /// (0 = use the built-in default).
  final BigInt turnTimeoutSecs;

  /// Number of consecutive per-block scores smoothed before a detection can fire
  /// (0 = engine default). Lower = snappier / more sensitive to brief or faint
  /// wake words; higher = fewer single-frame false triggers. A/B-tunable from the
  /// settings screen to dial in far-field responsiveness on hardware.
  final int smoothingWindow;

  /// Detection-gate criterion. `false` (default) fires on the *average* of the
  /// smoothing window clearing `threshold`; `true` fires as soon as the *peak*
  /// score in the window clears it — far more responsive to short/quiet "hey
  /// jarvis" utterances (whose confidence peaks for a single block and is
  /// otherwise diluted by the surrounding low blocks) at the cost of a slightly
  /// higher false-trigger rate.
  final bool fireOnPeak;

  /// Speaker playback buffer depth in seconds (0 = engine default). Sized to hold
  /// a whole spoken reply so long TTS answers are not truncated when the network
  /// delivers audio faster than real-time playback drains it. A/B-tunable.
  final int playbackBufferSecs;

  /// Software capture gain in **decibels**, applied to the 16 kHz mono audio right
  /// after resampling — i.e. to both the wake-word detector input *and* the PCM
  /// streamed to the Core. `0.0` (default) is unity/no-op. Positive values boost a
  /// quiet far-field signal; it is the in-app, root-free analogue of the AEC shim's
  /// `persist.vendor.amznaec.gain_db` makeup gain (which the sandboxed app cannot
  /// set). Clamped to `[0, 36]` dB and the boosted signal is clamped back into i16
  /// range so it never overflows the model input. A/B-tunable from the settings
  /// screen. Applies on both the `cpal` and `AudioRecord` capture paths.
  final double captureGainDb;

  /// **Android only.** Use the Kotlin `AudioRecord` capture layer instead of
  /// `cpal`, to reach the HAL's far-field `VOICE_RECOGNITION` source (array
  /// beamforming) + platform audio effects. `false` (default) keeps the `cpal`
  /// path; ignored entirely off-Android. A/B-tunable from the settings screen.
  final bool useAudiorecord;

  /// `android.media.MediaRecorder.AudioSource` for the AudioRecord path
  /// (6 = `VOICE_RECOGNITION`, 7 = `VOICE_COMMUNICATION`, 1 = `MIC`). Only used
  /// when `use_audiorecord` is set.
  final int micSource;

  /// Attach the platform `AcousticEchoCanceler` to the AudioRecord session (if the
  /// device offers it). Default off — the host-side WebRTC APM does AEC, and prior
  /// on-hardware testing found this device's platform AEC did not actually cancel.
  final bool platformAec;

  /// Attach the platform `AutomaticGainControl` to the AudioRecord session (if
  /// available). Helps the Echo Show's quiet far-field pickup.
  final bool platformAgc;

  /// Attach the platform `NoiseSuppressor` to the AudioRecord session (if available).
  final bool platformNs;

  /// **Android only.** Use the front camera as a proximity sensor: a cheap
  /// frame-motion detector runs on low-res luma frames and, when someone
  /// approaches, the UI brightens the idle screen (dimming again after a quiet
  /// period). `false` (default off-Android) disables the camera entirely — no
  /// frames are ever captured. See `camera/presence.rs` and Plan.MD §5.
  final bool cameraProximity;

  /// Mean absolute per-pixel luma delta (0..255) above which a frame counts as
  /// motion. `0` uses the engine default (`presence::DEFAULT_MOTION_THRESHOLD`).
  /// Lower = more sensitive (brightens on fainter/farther movement) at the cost of
  /// more false wakes from noise/lighting; A/B-tunable.
  final double proximityMotionThreshold;

  /// Seconds of no motion before the screen is allowed to dim again. `0` uses the
  /// engine default (`presence::DEFAULT_RELEASE`).
  final int proximityReleaseSecs;

  const WakeWordConfig({
    required this.melspecModelPath,
    required this.embeddingModelPath,
    required this.wakewordModelPath,
    required this.modelName,
    required this.threshold,
    required this.activeThreshold,
    required this.discoveryTimeoutSecs,
    required this.orchestratorKey,
    required this.turnTimeoutSecs,
    required this.smoothingWindow,
    required this.fireOnPeak,
    required this.playbackBufferSecs,
    required this.captureGainDb,
    required this.useAudiorecord,
    required this.micSource,
    required this.platformAec,
    required this.platformAgc,
    required this.platformNs,
    required this.cameraProximity,
    required this.proximityMotionThreshold,
    required this.proximityReleaseSecs,
  });

  @override
  int get hashCode =>
      melspecModelPath.hashCode ^
      embeddingModelPath.hashCode ^
      wakewordModelPath.hashCode ^
      modelName.hashCode ^
      threshold.hashCode ^
      activeThreshold.hashCode ^
      discoveryTimeoutSecs.hashCode ^
      orchestratorKey.hashCode ^
      turnTimeoutSecs.hashCode ^
      smoothingWindow.hashCode ^
      fireOnPeak.hashCode ^
      playbackBufferSecs.hashCode ^
      captureGainDb.hashCode ^
      useAudiorecord.hashCode ^
      micSource.hashCode ^
      platformAec.hashCode ^
      platformAgc.hashCode ^
      platformNs.hashCode ^
      cameraProximity.hashCode ^
      proximityMotionThreshold.hashCode ^
      proximityReleaseSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WakeWordConfig &&
          runtimeType == other.runtimeType &&
          melspecModelPath == other.melspecModelPath &&
          embeddingModelPath == other.embeddingModelPath &&
          wakewordModelPath == other.wakewordModelPath &&
          modelName == other.modelName &&
          threshold == other.threshold &&
          activeThreshold == other.activeThreshold &&
          discoveryTimeoutSecs == other.discoveryTimeoutSecs &&
          orchestratorKey == other.orchestratorKey &&
          turnTimeoutSecs == other.turnTimeoutSecs &&
          smoothingWindow == other.smoothingWindow &&
          fireOnPeak == other.fireOnPeak &&
          playbackBufferSecs == other.playbackBufferSecs &&
          captureGainDb == other.captureGainDb &&
          useAudiorecord == other.useAudiorecord &&
          micSource == other.micSource &&
          platformAec == other.platformAec &&
          platformAgc == other.platformAgc &&
          platformNs == other.platformNs &&
          cameraProximity == other.cameraProximity &&
          proximityMotionThreshold == other.proximityMotionThreshold &&
          proximityReleaseSecs == other.proximityReleaseSecs;
}

/// A single event streamed from the Rust engine to the Flutter UI. Modeled as a
/// flat struct with a `kind` tag (rather than a data-carrying enum) so the FRB
/// boundary stays dependency-free; fields not relevant to a given `kind` carry
/// neutral defaults. `Clone` lets the engine fan the sink out to the Phase-3
/// Wyoming turn task (which emits on the same stream).
class WakeWordEvent {
  final WakeWordEventKind kind;

  /// Status / error text (`Status`, `Error`).
  final String message;

  /// Capture device name (`Started`).
  final String device;

  /// Device-native capture rate in Hz (`Started`).
  final int deviceSampleRate;

  /// Device channel count before mono downmix (`Started`).
  final int channels;

  /// Input RMS level (`Level`).
  final double rms;

  /// Wake-word confidence in [0, 1] — the raw current-block score (`Level`,
  /// diagnostics) or the smoothed score that fired (`Detected`).
  final double score;

  /// The smoothed score the detection gate actually tests (average, or peak in
  /// peak mode) in [0, 1]. Carried on `Level` events so the audio-diagnostics
  /// screen can show the value being compared against the threshold; 0 otherwise.
  final double avgScore;

  /// The wake-word detection threshold currently in effect in [0, 1] (the idle
  /// threshold, or the raised active threshold during a turn). Carried on `Level`
  /// events so the diagnostics meter can draw the firing line; 0 otherwise.
  final double threshold;

  /// The software capture gain in dB currently applied to the mic signal. Carried
  /// on `Level` events so the diagnostics screen reflects live gain changes; 0
  /// otherwise.
  final double gainDb;

  /// Wake-word name that fired (`Detected`).
  final String model;

  /// Recognized speech (`Transcript`).
  final String transcript;

  /// One streamed reply-token fragment (`ReplyToken`).
  final String reply;

  /// Timer id (`TimerStarted` / `TimerFinished` / `TimerCancelled`). Stable for
  /// the life of one timer so the UI can add/remove the right chip.
  final int timerId;

  /// Timer's spoken label, empty when unlabeled (`TimerStarted`/`TimerFinished`).
  final String timerLabel;

  /// Full timer duration in seconds at start (`TimerStarted`); the UI counts down
  /// from `now + timer_remaining_secs`. Zero for finished/cancelled.
  final int timerRemainingSecs;

  /// Camera proximity state (`Presence`): `true` = someone approached (brighten),
  /// `false` = quiet long enough to dim. Neutral `false` for every other kind.
  final bool present;

  /// The parsed recipe as a JSON string (`ShowRecipe`); empty for every other kind.
  /// The UI decodes it into the recipe-mode tabs.
  final String recipeJson;

  /// The weather report as a JSON string (`ShowWeather` / `WeatherCurrent`); empty
  /// for every other kind. The UI decodes it into the weather screen + the ambient
  /// clock indicator.
  final String weatherJson;

  /// The place report as a JSON string (`ShowPlace`); empty for every other kind. The
  /// UI decodes it into the place card.
  final String placeJson;

  /// The recipe navigation/scroll argument: the target tab (`RecipeNavigate`) or the
  /// scroll direction (`RecipeScroll`). Empty for every other kind.
  final String recipeAction;

  const WakeWordEvent({
    required this.kind,
    required this.message,
    required this.device,
    required this.deviceSampleRate,
    required this.channels,
    required this.rms,
    required this.score,
    required this.avgScore,
    required this.threshold,
    required this.gainDb,
    required this.model,
    required this.transcript,
    required this.reply,
    required this.timerId,
    required this.timerLabel,
    required this.timerRemainingSecs,
    required this.present,
    required this.recipeJson,
    required this.weatherJson,
    required this.placeJson,
    required this.recipeAction,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      device.hashCode ^
      deviceSampleRate.hashCode ^
      channels.hashCode ^
      rms.hashCode ^
      score.hashCode ^
      avgScore.hashCode ^
      threshold.hashCode ^
      gainDb.hashCode ^
      model.hashCode ^
      transcript.hashCode ^
      reply.hashCode ^
      timerId.hashCode ^
      timerLabel.hashCode ^
      timerRemainingSecs.hashCode ^
      present.hashCode ^
      recipeJson.hashCode ^
      weatherJson.hashCode ^
      placeJson.hashCode ^
      recipeAction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WakeWordEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          device == other.device &&
          deviceSampleRate == other.deviceSampleRate &&
          channels == other.channels &&
          rms == other.rms &&
          score == other.score &&
          avgScore == other.avgScore &&
          threshold == other.threshold &&
          gainDb == other.gainDb &&
          model == other.model &&
          transcript == other.transcript &&
          reply == other.reply &&
          timerId == other.timerId &&
          timerLabel == other.timerLabel &&
          timerRemainingSecs == other.timerRemainingSecs &&
          present == other.present &&
          recipeJson == other.recipeJson &&
          weatherJson == other.weatherJson &&
          placeJson == other.placeJson &&
          recipeAction == other.recipeAction;
}

/// Discriminates the kind of [`WakeWordEvent`]. A unit-only enum so FRB maps it
/// to a plain Dart `enum` (no `freezed` codegen dependency needed).
enum WakeWordEventKind {
  /// Capture started; `device`/`device_sample_rate`/`channels` are populated.
  started,

  /// Informational status in `message` (e.g. model loaded, capture-only).
  status,

  /// Periodic input level in `rms` (~0.0..1.0) — proves capture is live even
  /// before a wake-word model is present. When a model is loaded it also carries
  /// the live wake-word diagnostics (`score`, `avg_score`, `threshold`, `gain_db`)
  /// that drive the audio-diagnostics screen.
  level,

  /// The wake word fired; `model` and `score` are populated.
  detected,

  /// Phase 3: a turn began — discovering/dialing the Wyoming host. `message`
  /// describes the resolved endpoint when known.
  connecting,

  /// Phase 3: connected to the Wyoming host; PCM is now streaming up.
  streaming,

  /// Phase 3: a transcript arrived from the STT server; `transcript` carries
  /// the recognized text.
  transcript,

  /// Phase 5: one streamed LLM reply-token fragment; `reply` carries the text.
  /// The UI appends these to render the reply token-by-token.
  replyToken,

  /// Phase 5: the reply's TTS audio has started and is now playing back through
  /// the speakers.
  speaking,

  /// Phase 5: the reply's TTS audio has finished playing out of the speaker — the
  /// playback ring drained naturally, or was flushed by a barge-in. UI-only: it
  /// signals that the on-screen reply text may be removed now that the audio has
  /// stopped. Fires *after* the turn has already returned to idle, because the
  /// device relays audio faster than real-time (see `engine/net.rs`).
  speakingDone,

  /// Follow-up listening: the assistant's reply was a question, so the device
  /// reopened the mic and is listening for the answer **without a wake word** (a
  /// fresh turn is starting). UI-only cue so the screen can show a "listening for
  /// your reply" affordance. Followed by the usual `Streaming`/`Transcript`/… of
  /// the follow-up turn. See `plans/Plan.MD` (Follow-up listening).
  listeningFollowup,

  /// Phase 3: the turn ended / the socket dropped; `message` gives the reason.
  /// The engine returns to idle wake-word listening.
  disconnected,

  /// The engine loop has stopped and capture has been torn down.
  stopped,

  /// A fatal error in `message`; the engine has stopped.
  error,

  /// Phase 2: a countdown timer started on the device. `timer_id`,
  /// `timer_label`, and `timer_remaining_secs` (the full duration) are populated;
  /// the UI shows a countdown from that deadline.
  timerStarted,

  /// Phase 2: a countdown timer reached zero (the alarm is sounding). `timer_id`
  /// and `timer_label` identify it.
  timerFinished,

  /// Phase 2: a running timer was cancelled. `timer_id` identifies it.
  timerCancelled,

  /// Recipe mode: the orchestrator pushed a parsed recipe to show on the display's
  /// 3-tab recipe screen. `recipe_json` carries the recipe as a JSON string (title,
  /// summary, source_url, image_url, servings, total_time, ingredients[], steps[])
  /// which the UI parses into the Overview / Ingredients / Steps tabs.
  showRecipe,

  /// Recipe mode: dismiss the recipe screen and return to the idle/ambient display.
  dismissRecipe,

  /// Weather mode: the orchestrator pushed a forecast to show full-screen on the
  /// weather screen. `weather_json` carries the report as a JSON string
  /// (location_label, units, current{…}, daily[]) which the UI parses into the big
  /// today panel + the 7-day row.
  showWeather,

  /// Weather mode: an ambient current-conditions refresh (from the persistent
  /// channel, or riding a `show`). `weather_json` carries the report; the UI updates
  /// the small icon + temperature beside the clock but does not open the full screen.
  weatherCurrent,

  /// Weather mode: dismiss the full-screen weather view and return to idle/ambient.
  dismissWeather,

  /// Place mode: the orchestrator pushed a place to show full-screen on the place
  /// card. `place_json` carries the report as a JSON string (name, address, hours[],
  /// open_now, rating, phone, website, photo_uri, …) which the UI parses into the card.
  showPlace,

  /// Place mode: dismiss the full-screen place card and return to idle/ambient.
  dismissPlace,

  /// Recipe mode: switch tab by voice. `recipe_action` is the target tab
  /// (`"overview"` / `"ingredients"` / `"steps"`).
  recipeNavigate,

  /// Recipe mode: scroll the active pane by voice. `recipe_action` is the direction
  /// (`"up"` / `"down"` a page, or `"top"` / `"bottom"`).
  recipeScroll,

  /// Font scaling: the orchestrator resolved a voice "increase font" / "decrease font"
  /// command. The direction (`"increase"` / `"decrease"`) rides the generic
  /// `recipe_action` field (the same string carrier as `RecipeScroll`). The UI bumps the
  /// global font scale and persists it.
  fontAdjust,

  /// Phase 5: the camera proximity sensor's present/absent state changed. `present`
  /// is `true` when someone has approached the display (brighten) and `false` when
  /// the room has been quiet long enough to dim again (Plan.MD §5). Emitted only on
  /// transitions, never per frame.
  presence,
}

/// Config for the persistent weather channel. Mirrors [`NotifyConfig`]; the
/// orchestrator is discovered over mDNS at connect time.
class WeatherConfig {
  /// Stable selection key (`instance_id` TXT) of the pinned orchestrator; empty =
  /// "Auto". Mirrors [`WakeWordConfig::orchestrator_key`].
  final String orchestratorKey;

  /// Seconds to browse `_wyoming._tcp` before falling back to the cached host
  /// (0 = built-in default).
  final BigInt discoveryTimeoutSecs;

  /// A stable identifier for this display, sent in the `anamanti-hello` frame.
  final String deviceId;

  /// A human-friendly label for this display (e.g. "Kitchen"), sent alongside
  /// `device_id` in the `anamanti-hello` frame (may be empty).
  final String deviceName;

  const WeatherConfig({
    required this.orchestratorKey,
    required this.discoveryTimeoutSecs,
    required this.deviceId,
    required this.deviceName,
  });

  @override
  int get hashCode =>
      orchestratorKey.hashCode ^
      discoveryTimeoutSecs.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherConfig &&
          runtimeType == other.runtimeType &&
          orchestratorKey == other.orchestratorKey &&
          discoveryTimeoutSecs == other.discoveryTimeoutSecs &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName;
}

/// One ambient current-conditions push from the orchestrator, streamed to Flutter.
/// `report_json` is the serialized weather report (location_label, units, current{…},
/// daily[]); the UI decodes it for the clock indicator (and refreshes the full screen
/// if it's open). Flat struct so the FRB boundary stays dependency-free.
class WeatherPush {
  final String reportJson;

  const WeatherPush({required this.reportJson});

  @override
  int get hashCode => reportJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherPush &&
          runtimeType == other.runtimeType &&
          reportJson == other.reportJson;
}
