// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_slot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

/// Fetch `{base_url}/latest.json`. Blocking; returns the parsed manifest.
Future<UpdateManifest> checkForUpdate({required String baseUrl}) =>
    RustLib.instance.api.crateApiUpdaterCheckForUpdate(baseUrl: baseUrl);

/// Stream-download `apk_url` to `dest_path`, verifying `expected_sha256` as the
/// bytes arrive, emitting [`DownloadProgress`] events. Replaces any download already
/// in flight. The final event is either `done = true` or carries an `error`; on
/// error (including cancel or hash mismatch) the partial file is removed.
Stream<DownloadProgress> downloadUpdate({
  required String apkUrl,
  required String expectedSha256,
  required String destPath,
}) => RustLib.instance.api.crateApiUpdaterDownloadUpdate(
  apkUrl: apkUrl,
  expectedSha256: expectedSha256,
  destPath: destPath,
);

/// Cancel an in-flight download (if any) and join its thread. Idempotent.
Future<void> cancelDownload() =>
    RustLib.instance.api.crateApiUpdaterCancelDownload();

/// One progress tick of a streaming download. Terminal states are `done == true`
/// (the verified APK is at the download path) or a non-empty `error`.
class DownloadProgress {
  /// Bytes written so far (or the final total on the `done` event).
  final PlatformInt64 downloaded;

  /// Total bytes from `Content-Length`, or 0 if the server didn't send it.
  final PlatformInt64 total;

  /// True only on the final event, once the download verified successfully.
  final bool done;

  /// Human-readable error (empty when none). A non-empty value is terminal.
  final String error;

  const DownloadProgress({
    required this.downloaded,
    required this.total,
    required this.done,
    required this.error,
  });

  @override
  int get hashCode =>
      downloaded.hashCode ^ total.hashCode ^ done.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          downloaded == other.downloaded &&
          total == other.total &&
          done == other.done &&
          error == other.error;
}

/// The update manifest (`latest.json`), reported to Dart.
class UpdateManifest {
  /// Android `versionCode` of the published build. Dart compares this against the
  /// running app's `versionCode` (read via the Kotlin updater channel).
  final PlatformInt64 versionCode;

  /// Human-readable `versionName` (e.g. "1.2.0").
  final String versionName;

  /// Absolute HTTPS URL of the APK to download.
  final String apkUrl;

  /// Expected lowercase-hex SHA-256 of the APK.
  final String sha256;

  /// Release notes to show the user.
  final String notes;

  const UpdateManifest({
    required this.versionCode,
    required this.versionName,
    required this.apkUrl,
    required this.sha256,
    required this.notes,
  });

  @override
  int get hashCode =>
      versionCode.hashCode ^
      versionName.hashCode ^
      apkUrl.hashCode ^
      sha256.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateManifest &&
          runtimeType == other.runtimeType &&
          versionCode == other.versionCode &&
          versionName == other.versionName &&
          apkUrl == other.apkUrl &&
          sha256 == other.sha256 &&
          notes == other.notes;
}
