// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine_target`

/// A friendly greeting from the native Rust engine.
///
/// The Flutter UI calls this on startup to confirm the cross-compiled shared
/// library loaded and the FRB bridge is live on the device.
String engineGreeting({required String name}) =>
    RustLib.instance.api.crateApiEngineEngineGreeting(name: name);

/// Reports the native engine's version and build target so the device can show
/// exactly which cross-compiled binary it is running.
String engineVersion() => RustLib.instance.api.crateApiEngineEngineVersion();
