// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `timeout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Read the orchestrator's current runtime settings.
Future<OrchestratorSettings> fetchOrchestratorSettings({
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsFetchOrchestratorSettings(
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Apply a settings change on the orchestrator and return the resulting settings.
Future<OrchestratorSettings> updateOrchestratorSettings({
  required SettingsUpdate update,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsUpdateOrchestratorSettings(
  update: update,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// List all persistent memory entries (settings memory management view).
Future<List<MemoryEntry>> listMemories({
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsListMemories(
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Delete one memory entry by id. Returns whether a row was removed.
Future<bool> deleteMemory({
  required PlatformInt64 id,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsDeleteMemory(
  id: id,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Delete every memory entry. Returns the number removed.
Future<int> clearMemories({required BigInt discoveryTimeoutSecs}) => RustLib
    .instance
    .api
    .crateApiSettingsClearMemories(discoveryTimeoutSecs: discoveryTimeoutSecs);

/// List the identified speakers (settings "People" view).
Future<List<SpeakerInfo>> listSpeakers({
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsListSpeakers(
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Name (or rename) a speaker. Returns whether the change was applied.
Future<bool> nameSpeaker({
  required String id,
  required String name,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsNameSpeaker(
  id: id,
  name: name,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Merge the `drop` speaker into `keep` (same person, two clusters). Returns
/// whether the merge was applied.
Future<bool> mergeSpeakers({
  required String keep,
  required String drop,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsMergeSpeakers(
  keep: keep,
  drop: drop,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Delete a speaker profile. Returns whether a profile was removed.
Future<bool> deleteSpeaker({
  required String id,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsDeleteSpeaker(
  id: id,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// One persistent memory entry, for the settings memory list.
class MemoryEntry {
  final PlatformInt64 id;

  /// `fact` or `preference`.
  final String kind;
  final String content;

  /// `explicit` (user asked) or `inferred` (auto-extracted).
  final String source;

  /// Unix seconds when the entry was stored.
  final PlatformInt64 createdAt;

  const MemoryEntry({
    required this.id,
    required this.kind,
    required this.content,
    required this.source,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      content.hashCode ^
      source.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          content == other.content &&
          source == other.source &&
          createdAt == other.createdAt;
}

/// The orchestrator's runtime settings, as reported by a describe/set response.
class OrchestratorSettings {
  /// Whether the request succeeded (a rejected change reports `false` with a
  /// human-readable `message`, leaving the previous settings in effect).
  final bool ok;

  /// Human-readable status/error (e.g. why a backend change was rejected).
  final String message;

  /// The active LLM backend label (`ollama` / `anthropic` / `mock`).
  final String llmBackend;

  /// The active model name, if the backend uses one.
  final String? llmModel;

  /// The active Piper voice, or `None` for the server default.
  final String? ttsVoice;

  /// Orchestrator VAD: end-of-speech trailing silence in ms (0 if unknown).
  final int endSilenceMs;

  /// Orchestrator VAD: speech-vs-noise RMS threshold (0 if unknown).
  final double voiceRmsThreshold;

  const OrchestratorSettings({
    required this.ok,
    required this.message,
    required this.llmBackend,
    this.llmModel,
    this.ttsVoice,
    required this.endSilenceMs,
    required this.voiceRmsThreshold,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      message.hashCode ^
      llmBackend.hashCode ^
      llmModel.hashCode ^
      ttsVoice.hashCode ^
      endSilenceMs.hashCode ^
      voiceRmsThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrchestratorSettings &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          message == other.message &&
          llmBackend == other.llmBackend &&
          llmModel == other.llmModel &&
          ttsVoice == other.ttsVoice &&
          endSilenceMs == other.endSilenceMs &&
          voiceRmsThreshold == other.voiceRmsThreshold;
}

/// A requested settings change from the screen. Absent fields are left unchanged.
class SettingsUpdate {
  /// New LLM backend label, or `None` to leave it unchanged.
  final String? llmBackend;

  /// New model name, or `None` to leave it unchanged.
  final String? llmModel;

  /// When `true`, apply `tts_voice` (a `None`/empty value clears the voice); when
  /// `false`, leave the voice unchanged.
  final bool setTtsVoice;

  /// The voice to set when `set_tts_voice` is `true`.
  final String? ttsVoice;

  /// New orchestrator VAD end-of-speech silence (ms), or `None` to leave it.
  final int? endSilenceMs;

  /// New orchestrator VAD speech RMS threshold, or `None` to leave it.
  final double? voiceRmsThreshold;

  const SettingsUpdate({
    this.llmBackend,
    this.llmModel,
    required this.setTtsVoice,
    this.ttsVoice,
    this.endSilenceMs,
    this.voiceRmsThreshold,
  });

  @override
  int get hashCode =>
      llmBackend.hashCode ^
      llmModel.hashCode ^
      setTtsVoice.hashCode ^
      ttsVoice.hashCode ^
      endSilenceMs.hashCode ^
      voiceRmsThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsUpdate &&
          runtimeType == other.runtimeType &&
          llmBackend == other.llmBackend &&
          llmModel == other.llmModel &&
          setTtsVoice == other.setTtsVoice &&
          ttsVoice == other.ttsVoice &&
          endSilenceMs == other.endSilenceMs &&
          voiceRmsThreshold == other.voiceRmsThreshold;
}

/// One identified speaker, for the settings "People" list (speaker_id_plan.md
/// Phase C).
class SpeakerInfo {
  /// Stable id (`spk-…`) referenced by memory + the graph.
  final String id;

  /// User-given name, or `None` while the cluster is still anonymous.
  final String? name;

  /// Whether a person has named this cluster (vs. auto-created).
  final bool labeled;

  /// How many utterances back this voiceprint.
  final PlatformInt64 samples;

  /// Unix seconds when the cluster was first heard.
  final PlatformInt64 createdAt;

  const SpeakerInfo({
    required this.id,
    this.name,
    required this.labeled,
    required this.samples,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      labeled.hashCode ^
      samples.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeakerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          labeled == other.labeled &&
          samples == other.samples &&
          createdAt == other.createdAt;
}
