// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `timeout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Read the orchestrator's current runtime settings.
Future<OrchestratorSettings> fetchOrchestratorSettings({
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsFetchOrchestratorSettings(
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Apply a settings change on the orchestrator and return the resulting settings.
Future<OrchestratorSettings> updateOrchestratorSettings({
  required SettingsUpdate update,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsUpdateOrchestratorSettings(
  update: update,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// List the orchestrator's selectable LLM models (Anthropic + OpenAI, scoped to the
/// last 12 months) for the settings model dropdown.
Future<List<ModelInfo>> listModels({required BigInt discoveryTimeoutSecs}) =>
    RustLib.instance.api.crateApiSettingsListModels(
      discoveryTimeoutSecs: discoveryTimeoutSecs,
    );

/// List all persistent memory entries (settings memory management view).
Future<List<MemoryEntry>> listMemories({
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsListMemories(
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Delete one memory entry by id. Returns whether a row was removed.
Future<bool> deleteMemory({
  required PlatformInt64 id,
  required BigInt discoveryTimeoutSecs,
}) => RustLib.instance.api.crateApiSettingsDeleteMemory(
  id: id,
  discoveryTimeoutSecs: discoveryTimeoutSecs,
);

/// Delete every memory entry. Returns the number removed.
Future<int> clearMemories({required BigInt discoveryTimeoutSecs}) => RustLib
    .instance
    .api
    .crateApiSettingsClearMemories(discoveryTimeoutSecs: discoveryTimeoutSecs);

/// One persistent memory entry, for the settings memory list.
class MemoryEntry {
  final PlatformInt64 id;

  /// `fact` or `preference`.
  final String kind;
  final String content;

  /// `explicit` (user asked) or `inferred` (auto-extracted).
  final String source;

  /// Unix seconds when the entry was stored.
  final PlatformInt64 createdAt;

  const MemoryEntry({
    required this.id,
    required this.kind,
    required this.content,
    required this.source,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      content.hashCode ^
      source.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          content == other.content &&
          source == other.source &&
          createdAt == other.createdAt;
}

/// One selectable LLM model for the settings model dropdown, as reported by the
/// orchestrator's catalog (scoped to the last 12 months per provider).
class ModelInfo {
  /// `anthropic` or `openai`.
  final String provider;

  /// The model id to send as the backend's model (e.g. `claude-opus-5`).
  final String id;

  /// A human-friendly label for the dropdown (falls back to `id`).
  final String label;

  const ModelInfo({
    required this.provider,
    required this.id,
    required this.label,
  });

  @override
  int get hashCode => provider.hashCode ^ id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          id == other.id &&
          label == other.label;
}

/// The orchestrator's runtime settings, as reported by a describe/set response.
class OrchestratorSettings {
  /// Whether the request succeeded (a rejected change reports `false` with a
  /// human-readable `message`, leaving the previous settings in effect).
  final bool ok;

  /// Human-readable status/error (e.g. why a backend change was rejected).
  final String message;

  /// The active LLM backend label (`ollama` / `anthropic` / `openai` / `mock`).
  final String llmBackend;

  /// The active model name, if the backend uses one.
  final String? llmModel;

  /// Anthropic auth mode: `apikey` or `subscription` (Claude OAuth).
  final String anthropicAuth;

  /// The active Piper voice, or `None` for the server default.
  final String? ttsVoice;

  /// Orchestrator VAD: end-of-speech trailing silence in ms (0 if unknown).
  final int endSilenceMs;

  /// Orchestrator VAD: speech-vs-noise RMS threshold (0 if unknown).
  final double voiceRmsThreshold;

  const OrchestratorSettings({
    required this.ok,
    required this.message,
    required this.llmBackend,
    this.llmModel,
    required this.anthropicAuth,
    this.ttsVoice,
    required this.endSilenceMs,
    required this.voiceRmsThreshold,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      message.hashCode ^
      llmBackend.hashCode ^
      llmModel.hashCode ^
      anthropicAuth.hashCode ^
      ttsVoice.hashCode ^
      endSilenceMs.hashCode ^
      voiceRmsThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrchestratorSettings &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          message == other.message &&
          llmBackend == other.llmBackend &&
          llmModel == other.llmModel &&
          anthropicAuth == other.anthropicAuth &&
          ttsVoice == other.ttsVoice &&
          endSilenceMs == other.endSilenceMs &&
          voiceRmsThreshold == other.voiceRmsThreshold;
}

/// A requested settings change from the screen. Absent fields are left unchanged.
class SettingsUpdate {
  /// New LLM backend label, or `None` to leave it unchanged.
  final String? llmBackend;

  /// New model name, or `None` to leave it unchanged.
  final String? llmModel;

  /// New Anthropic auth mode (`apikey`/`subscription`), or `None` to leave it.
  final String? anthropicAuth;

  /// When `true`, apply `tts_voice` (a `None`/empty value clears the voice); when
  /// `false`, leave the voice unchanged.
  final bool setTtsVoice;

  /// The voice to set when `set_tts_voice` is `true`.
  final String? ttsVoice;

  /// New orchestrator VAD end-of-speech silence (ms), or `None` to leave it.
  final int? endSilenceMs;

  /// New orchestrator VAD speech RMS threshold, or `None` to leave it.
  final double? voiceRmsThreshold;

  const SettingsUpdate({
    this.llmBackend,
    this.llmModel,
    this.anthropicAuth,
    required this.setTtsVoice,
    this.ttsVoice,
    this.endSilenceMs,
    this.voiceRmsThreshold,
  });

  @override
  int get hashCode =>
      llmBackend.hashCode ^
      llmModel.hashCode ^
      anthropicAuth.hashCode ^
      setTtsVoice.hashCode ^
      ttsVoice.hashCode ^
      endSilenceMs.hashCode ^
      voiceRmsThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsUpdate &&
          runtimeType == other.runtimeType &&
          llmBackend == other.llmBackend &&
          llmModel == other.llmModel &&
          anthropicAuth == other.anthropicAuth &&
          setTtsVoice == other.setTtsVoice &&
          ttsVoice == other.ttsVoice &&
          endSilenceMs == other.endSilenceMs &&
          voiceRmsThreshold == other.voiceRmsThreshold;
}
